// src/pages/Clientes.tsx
import React, { useState, useEffect } from 'react';
import Modal from '../components/Modal';
import PageLayout from '../components/PageLayout';
import { useSeniorMode } from '../contexts/SeniorModeContext';

interface Praca {
  id: number;
  codigo: string;
  nome: string;
}

interface Rota {
  id: number;
  codigo: string;
  nome?: string;
  praca_id?: number;
}

interface Cliente {
  id?: number;
  nome: string;
  cpf_cnpj: string;
  ie_rg?: string;
  endereco?: string;
  bairro?: string;
  cidade: string;
  estado?: string;
  cep?: string;
  telefone: string;
  email?: string;
  limite_credito?: number;
  data_nascimento?: string;
  nome_mae?: string;
  nome_pai?: string;
  naturalidade?: string;
  rota_id?: number;
  praca_id?: number; // NEW: FK para praça
  tabela_preco?: 'A' | 'B'; // NEW: Tabela de preço (A ou B)
  referencia?: string;
  ativo: boolean;
  data_cadastro?: string;
  hora_visita_inicio?: string;
  hora_visita_fim?: string;
  dias_visita?: string;
  observacoes?: string;
}

const Clientes: React.FC = () => {
  const [clientes, setClientes] = useState<Cliente[]>([]);
  const [pracas, setPracas] = useState<Praca[]>([]);
  const [rotas, setRotas] = useState<Rota[]>([]);
  const [mostrarForm, setMostrarForm] = useState(false);
  const [clienteEditando, setClienteEditando] = useState<Cliente | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const { isSeniorMode } = useSeniorMode();

  useEffect(() => {
    carregarClientes();
    carregarPracas();
    carregarRotas();
  }, []);

  const carregarClientes = async () => {
    setLoading(true);
    try {
      const response = await fetch('http://localhost:3000/api/clientes');
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data: Cliente[] = await response.json();
      setClientes(data);
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao carregar clientes: ${message}`);
      console.error("Erro ao carregar clientes:", e);
    } finally {
      setLoading(false);
    }
  };

  const carregarPracas = async () => {
    try {
      const response = await fetch('http://localhost:3000/api/pracas');
      if (response.ok) {
        const data: Praca[] = await response.json();
        setPracas(data);
      }
    } catch (e) {
      console.error('Erro ao carregar praças:', e);
    }
  };

  const carregarRotas = async () => {
    try {
      const response = await fetch('http://localhost:3000/api/rotas');
      if (response.ok) {
        const data: Rota[] = await response.json();
        setRotas(data);
      }
    } catch (e) {
      console.error('Erro ao carregar rotas:', e);
    }
  };

  const salvarCliente = async (cliente: Cliente) => {
    setError(null);
    setSuccess(null);
    try {
      let response;
      if (cliente.id) {
        response = await fetch(`http://localhost:3000/api/clientes/${cliente.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(cliente),
        });
      } else {
        response = await fetch('http://localhost:3000/api/clientes', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(cliente),
        });
      }

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarClientes();
      setMostrarForm(false);
      setClienteEditando(null);
      setSuccess(`Cliente ${cliente.id ? 'atualizado' : 'criado'} com sucesso!`);
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao salvar cliente: ${message}`);
      console.error("Erro ao salvar cliente:", e);
    }
  };

  const deletarCliente = async (id: number) => {
    if (!window.confirm('Confirmar exclusão?')) {
      return;
    }
    setError(null);
    setSuccess(null);
    try {
      const response = await fetch(`http://localhost:3000/api/clientes/${id}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarClientes();
      setSuccess("Cliente excluído com sucesso!");
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao deletar cliente: ${message}`);
      console.error("Erro ao deletar cliente:", e);
    }
  };

  const actions = (
    <button
      onClick={() => { setClienteEditando(null); setMostrarForm(true); }}
      className={`${isSeniorMode ? 'bg-blue-600 hover:bg-blue-700 py-3 px-6 text-xl' : 'bg-blue-500 hover:bg-blue-600 py-2 px-4'} text-white font-bold rounded-md transition-colors`}
    >
      {isSeniorMode ? '+ Adicionar Novo Cliente' : '+ Novo Cliente'}
    </button>
  );

  return (
    <PageLayout
      title="Gerenciar Clientes"
      actions={actions}
      isLoading={loading}
      error={error}
      success={success}
      onErrorClose={() => setError(null)}
      onSuccessClose={() => setSuccess(null)}
    >
      <Modal isOpen={mostrarForm} onClose={() => { setMostrarForm(false); setClienteEditando(null); }}>
        <ClienteForm
          cliente={clienteEditando}
          pracas={pracas}
          rotas={rotas}
          onSave={salvarCliente}
          onCancel={() => { setMostrarForm(false); setClienteEditando(null); }}
        />
      </Modal>

      <div className="table-container overflow-x-auto">
        <table className={`min-w-full bg-white border border-gray-200 ${isSeniorMode ? 'text-lg' : 'text-sm'}`}>
          <thead>
            <tr className="bg-gray-100 border-b">
              <th className="py-3 px-4 text-left font-semibold text-gray-600">Nome</th>
              <th className="py-3 px-4 text-left font-semibold text-gray-600">Telefone</th>
              <th className="py-3 px-4 text-left font-semibold text-gray-600">Cidade</th>
              {!isSeniorMode && <th className="py-3 px-4 text-left font-semibold text-gray-600">CPF/CNPJ</th>}
              {!isSeniorMode && <th className="py-3 px-4 text-left font-semibold text-gray-600">Status</th>}
              <th className="py-3 px-4 text-left font-semibold text-gray-600">Ações</th>
            </tr>
          </thead>
          <tbody>
            {clientes.map(cliente => (
              <tr key={cliente.id} className="border-b hover:bg-gray-50">
                <td className="py-3 px-4 text-gray-700">{cliente.nome}</td>
                <td className="py-3 px-4 text-gray-700">{cliente.telefone}</td>
                <td className="py-3 px-4 text-gray-700">{cliente.cidade}</td>
                {!isSeniorMode && <td className="py-3 px-4 text-gray-700">{cliente.cpf_cnpj}</td>}
                {!isSeniorMode && <td className="py-3 px-4 text-gray-700">{cliente.ativo ? 'Ativo' : 'Inativo'}</td>}
                <td className="py-3 px-4">
                  <button
                    onClick={() => { setClienteEditando(cliente); setMostrarForm(true); }}
                    className={`${isSeniorMode ? 'py-2 px-4 text-lg' : 'py-1 px-3'} bg-yellow-500 hover:bg-yellow-600 text-white font-bold rounded-md mr-2 transition-colors`}
                  >
                    Editar
                  </button>
                  <button
                    onClick={() => deletarCliente(cliente.id!)}
                    className={`${isSeniorMode ? 'py-2 px-4 text-lg' : 'py-1 px-3'} bg-red-500 hover:bg-red-600 text-white font-bold rounded-md transition-colors`}
                  >
                    Excluir
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </PageLayout>
  );
};

const ClienteForm: React.FC<{
  cliente: Cliente | null;
  pracas: Praca[];
  rotas: Rota[];
  onSave: (cliente: Cliente) => void;
  onCancel: () => void;
}> = ({ cliente, pracas, rotas, onSave, onCancel }) => {
  const { isSeniorMode } = useSeniorMode();
  const [formData, setFormData] = useState<Cliente>(
    cliente || {
      nome: '',
      cpf_cnpj: '',
      telefone: '',
      cidade: '',
      ativo: true,
      praca_id: undefined,
      rota_id: undefined,
      tabela_preco: 'A',
    }
  );

  // Filtrar rotas pela praça selecionada
  const rotasFiltradas = formData.praca_id
    ? rotas.filter(r => r.praca_id === formData.praca_id)
    : rotas;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <div className={`w-full bg-white shadow-2xl rounded-2xl ${isSeniorMode ? 'p-8' : 'p-10'}`}>
      <h2 className={`${isSeniorMode ? 'text-5xl mb-8' : 'text-4xl mb-4'} font-bold text-gray-800 text-center`}>
        {cliente ? 'Editar Cliente' : 'Novo Cliente'}
      </h2>

      <form onSubmit={handleSubmit} className="space-y-8">
        <div>
          <label htmlFor="nome" className={`block font-semibold text-gray-700 mb-2 ${isSeniorMode ? 'text-2xl' : 'text-xl'}`}>
            Nome Completo
          </label>
          <input
            type="text"
            id="nome"
            value={formData.nome}
            onChange={e => setFormData({ ...formData, nome: e.target.value })}
            required
            className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? 'py-4 px-6 text-2xl' : 'py-3 px-4 text-lg'}`}
          />
        </div>

        <div>
          <label htmlFor="telefone" className={`block font-semibold text-gray-700 mb-2 ${isSeniorMode ? 'text-2xl' : 'text-xl'}`}>
            Telefone
          </label>
          <input
            type="text"
            id="telefone"
            value={formData.telefone}
            onChange={e => setFormData({ ...formData, telefone: e.target.value })}
            className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? 'py-4 px-6 text-2xl' : 'py-3 px-4 text-lg'}`}
          />
        </div>

        <div>
          <label htmlFor="cidade" className={`block font-semibold text-gray-700 mb-2 ${isSeniorMode ? 'text-2xl' : 'text-xl'}`}>
            Cidade
          </label>
          <input
            type="text"
            id="cidade"
            value={formData.cidade}
            onChange={e => setFormData({ ...formData, cidade: e.target.value })}
            className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? 'py-4 px-6 text-2xl' : 'py-3 px-4 text-lg'}`}
          />
        </div>

        {/* NEW: Praça, Rota e Tabela de Preço */}
        <div>
          <label className={`block font-semibold text-gray-700 mb-2 ${isSeniorMode ? 'text-2xl' : 'text-xl'}`}>
            Localização e Preços
          </label>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <select
              value={formData.praca_id || ''}
              onChange={e => {
                const pracaId = e.target.value ? parseInt(e.target.value) : undefined;
                setFormData({ ...formData, praca_id: pracaId, rota_id: undefined });
              }}
              className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? 'py-4 px-6 text-2xl' : 'py-3 px-4 text-lg'}`}
            >
              <option value="">Selecione uma Praça</option>
              {pracas.map(praca => (
                <option key={praca.id} value={praca.id}>{praca.codigo} - {praca.nome}</option>
              ))}
            </select>
            <select
              value={formData.rota_id || ''}
              onChange={e => setFormData({ ...formData, rota_id: e.target.value ? parseInt(e.target.value) : undefined })}
              className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? 'py-4 px-6 text-2xl' : 'py-3 px-4 text-lg'}`}
            >
              <option value="">Selecione uma Rota</option>
              {rotasFiltradas.map(rota => (
                <option key={rota.id} value={rota.id}>{rota.codigo} - {rota.nome || ''}</option>
              ))}
            </select>
            <select
              value={formData.tabela_preco || 'A'}
              onChange={e => setFormData({ ...formData, tabela_preco: e.target.value as 'A' | 'B' })}
              className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent ${isSeniorMode ? 'py-4 px-6 text-2xl' : 'py-3 px-4 text-lg'}`}
            >
              <option value="A">Tabela A (Padrão)</option>
              <option value="B">Tabela B (Margem Maior)</option>
            </select>
          </div>
        </div>

        {!isSeniorMode && (
          <>
            <div>
              <label htmlFor="cpf_cnpj" className="block text-xl font-semibold text-gray-700 mb-2">
                CPF ou CNPJ
              </label>
              <input
                type="text"
                id="cpf_cnpj"
                value={formData.cpf_cnpj}
                onChange={e => setFormData({ ...formData, cpf_cnpj: e.target.value })}
                className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div className="flex items-center">
              <input
                type="checkbox"
                id="ativo"
                checked={formData.ativo}
                onChange={e => setFormData({ ...formData, ativo: e.target.checked })}
                className="h-6 w-6 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
              />
              <label htmlFor="ativo" className="ml-3 block text-xl font-semibold text-gray-700">
                Cliente Ativo
              </label>
            </div>
          </>
        )}

        <div className="form-actions flex justify-center gap-6 pt-4">
          <button
            type="button"
            onClick={onCancel}
            className={`w-1/3 bg-gray-500 hover:bg-gray-600 text-white font-bold rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300 ${isSeniorMode ? 'py-6 px-10 text-2xl' : 'py-4 px-8 text-xl'}`}
          >
            Cancelar
          </button>
          <button
            type="submit"
            className={`w-1/3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300 ${isSeniorMode ? 'py-6 px-10 text-2xl' : 'py-4 px-8 text-xl'}`}
          >
            {isSeniorMode ? 'Salvar Cliente' : 'Salvar'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default Clientes;

// src/routes/clientes/+page.svelte
<script lang="ts">
  import * as Card from "$lib/components/ui/card/index.js";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
  import * as Table from "$lib/components/ui/table/index.js";
  import { Button } from "@/components/ui/button/index";
  import Checkbox from "@/components/ui/checkbox/checkbox.svelte";
  import { Input } from "@/components/ui/input/index";
  import { Label } from "@/components/ui/label/index";
  import db, { queryHelper } from "@/db/db.svelte";
  import type { Cliente, Praca, Rota, Vendedor } from "@/types";
  import Ellipsis from "@lucide/svelte/icons/ellipsis";
  import PencilLine from "@lucide/svelte/icons/pencil-line";
  import Plus from "@lucide/svelte/icons/plus";
  import Search from "@lucide/svelte/icons/search";
  import Trash2 from "@lucide/svelte/icons/trash-2";
  import Users from "@lucide/svelte/icons/users";
  import { onMount } from "svelte";
  import { toast } from "svelte-sonner";

  let clientes = $state<Array<Cliente>>([]);
  let vendedores = $state<Array<Vendedor>>([]);
  let pracas = $state<Array<Praca>>([]);
  let rotas = $state<Array<Rota>>([]);
  let dialog = $state<string | null>(null);
  let searchQuery = $state("");

  let clientData = $state<Partial<Cliente>>({
    nome: "",
    telefone: "",
    cidade: "",
    cpf_cnpj: "",
    vendedor_id: 0,
    praca_id: 0,
    rota_id: 0,
    tabela_preco: "A",
    ativo: true,
  });

  let filteredClientes = $derived(
    searchQuery
      ? clientes.filter(
          (c) =>
            c.nome.toLowerCase().includes(searchQuery.toLowerCase()) ||
            (c.cpf_cnpj && c.cpf_cnpj.includes(searchQuery))
        )
      : clientes
  );

  let filteredRotas = $derived(
    clientData.praca_id
      ? rotas.filter((r) => r.praca_id === clientData.praca_id)
      : []
  );

  async function save() {
    try {
      delete clientData.data_cadastro;
      let q = queryHelper(clientData);
      let query = "";

      if (clientData.id) {
        query = `UPDATE clientes SET ${q.setClauses} WHERE id = ${clientData.id}`;
      } else {
        query = `INSERT INTO clientes (${q.columns}) VALUES (${q.placeholders})`;
      }

      await db.execute(query, q.values);

      await load();
      dialog = null;
      toast.success(
        `Cliente ${clientData.id ? "atualizado" : "criado"} com sucesso!`
      );
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      toast.error(`Falha ao salvar cliente: ${message}`);
      console.error("Erro ao salvar cliente:", e);
      dialog = null;
    }
  }

  async function delete_(id: number) {
    try {
      await db.execute("DELETE FROM clientes WHERE id = $1", [id]);

      await load();
      toast.success("Cliente excluído com sucesso!");
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      toast.error(`Falha ao deletar cliente: ${message}`);
      console.error("Erro ao deletar cliente:", e);
    }
  }

  async function load() {
    try {
      clientes = (await db.select(
        "SELECT * FROM clientes",
        []
      )) as Array<Cliente>;
      vendedores = (await db.select(
        "SELECT * FROM vendedores",
        []
      )) as Array<Vendedor>;
      pracas = (await db.select("SELECT * FROM pracas", [])) as Array<Praca>;
      rotas = (await db.select("SELECT * FROM rotas", [])) as Array<Rota>;
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      toast.error(`Falha ao carregar clientes: ${message}`);
      console.error("Erro ao carregar clientes:", e);
    } finally {
    }
  }

  onMount(() => load());
</script>

<Card.Root class="m-10">
  <Card.Header class="flex w-full">
    <Card.Title class="text-3xl flex items-center gap-2">
      <Users class="h-8 w-8 text-primary" /> Gerenciamento de Clientes
    </Card.Title>
    <Button
      class="ml-auto cursor-pointer"
      variant="outline"
      size="lg"
      onclick={() => {
        dialog = "new";
      }}
    >
      Novo cliente
      <Plus class="stroke-2" />
    </Button>
  </Card.Header>
  <Card.Content>
    <div class="mb-6 flex items-center gap-4">
      <div class="relative flex-1 max-w-sm">
        <Search
          class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"
        />
        <Input
          type="search"
          placeholder="Pesquisar por nome ou CPF/CNPJ..."
          class="pl-8"
          bind:value={searchQuery}
        />
      </div>
    </div>

    <Table.Root>
      <Table.Header>
        <Table.Row>
          <Table.Head>Nome</Table.Head>
          <Table.Head>CPF/CNPJ</Table.Head>
          <Table.Head>Telefone</Table.Head>
          <Table.Head>Cidade</Table.Head>
          <Table.Head class="w-12.5"></Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#each filteredClientes as client (client.id)}
          <Table.Row>
            <Table.Cell class="font-medium text-primary">
              {client.nome}
            </Table.Cell>
            <Table.Cell>{client.cpf_cnpj}</Table.Cell>
            <Table.Cell>{client.telefone}</Table.Cell>
            <Table.Cell class="text-primary">
              {client.cidade}
            </Table.Cell>
            <Table.Cell>
              <Button
                variant="ghost"
                size="icon"
                onclick={() => {
                  clientData = { ...client };
                  dialog = "edit";
                }}
              >
                <PencilLine class="h-4 w-4 stroke-lime-500! stroke-3" />
              </Button>

              <Button
                variant="ghost"
                size="icon-lg"
                onclick={() => delete_(client.id)}
              >
                <Trash2 class="h-4 w-4 stroke-red-500! stroke-3" />
              </Button>
            </Table.Cell>
          </Table.Row>
        {/each}
      </Table.Body>
    </Table.Root>
  </Card.Content>
</Card.Root>

<Dialog.Root
  open={dialog != null}
  onOpenChange={(e) =>
    e
      ? null
      : ((dialog = null),
        (clientData = {
          nome: "",
          telefone: "",
          cidade: "",
          cpf_cnpj: "",
          vendedor_id: 0,
          praca_id: 0,
          rota_id: 0,
          tabela_preco: "A",
          ativo: true,
        }))}
>
  <Dialog.Content class="gap-10">
    <Dialog.Header>
      <Dialog.Title>
        {#if dialog == "new"}
          Novo Cliente
        {:else if dialog == "edit"}
          Editar Cliente
        {/if}
      </Dialog.Title>
    </Dialog.Header>

    <div class="flex flex-col gap-5">
      <div class="flex flex-col gap-3">
        <Label for="name">Nome Completo:</Label>
        <Input
          id="name"
          bind:value={clientData.nome}
          placeholder="Fellype Samuel..."
        />
      </div>

      <div class="flex flex-col gap-3">
        <Label for="phone">Telefone:</Label>
        <Input
          id="phone"
          bind:value={clientData.telefone}
          placeholder="(21) 12345-6789..."
        />
      </div>

      <div class="flex flex-col gap-3">
        <Label for="city">Cidade:</Label>
        <Input
          id="city"
          bind:value={clientData.cidade}
          placeholder="Rio de Janeiro..."
        />
      </div>

      <div class="flex flex-col gap-3">
        <Label for="cpf_cnpj">CPF/CNPJ:</Label>
        <Input
          id="cpf_cnpj"
          bind:value={clientData.cpf_cnpj}
          placeholder="123.456.789-10..."
        />
      </div>

      <div class="flex flex-col gap-3">
        <Label for="vendedor">Vendedor:</Label>
        <select
          id="vendedor"
          bind:value={clientData.vendedor_id}
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          required
        >
          <option value={0}>Selecione um vendedor...</option>
          {#each vendedores as v}
            <option value={v.id}>{v.codigo} - {v.nome}</option>
          {/each}
        </select>
      </div>

      <div class="grid grid-cols-2 gap-3">
        <div class="flex flex-col gap-3">
          <Label for="praca">Praça:</Label>
          <select
            id="praca"
            bind:value={clientData.praca_id}
            class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          >
            <option value={0}>Selecione...</option>
            {#each pracas as p}
              <option value={p.id}>{p.codigo} - {p.nome}</option>
            {/each}
          </select>
        </div>
        <div class="flex flex-col gap-3">
          <Label for="rota">Rota:</Label>
          <select
            id="rota"
            bind:value={clientData.rota_id}
            class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            disabled={!clientData.praca_id}
          >
            <option value={0}>Selecione...</option>
            {#each filteredRotas as r}
              <option value={r.id}>{r.codigo} - {r.nome}</option>
            {/each}
          </select>
        </div>
      </div>

      <div class="flex flex-col gap-3">
        <Label for="tabela">Tabela de Preço:</Label>
        <select
          id="tabela"
          bind:value={clientData.tabela_preco}
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        >
          <option value="A">Tabela A (Padrão)</option>
          <option value="B">Tabela B (Especial)</option>
        </select>
      </div>

      <div class="flex gap-3">
        <Checkbox id="active" bind:checked={clientData.ativo} />
        <Label for="active">Cliente ativo</Label>
      </div>
    </div>
    <Dialog.Footer class="grid grid-cols-2 gap-5">
      <Button variant="outline" onclick={() => (dialog = null)}>
        Cancelar
      </Button>
      <Button onclick={save}>Salvar</Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
