// src/routes/produtos/+page.svelte
<script lang="ts">
    import Package from "@lucide/svelte/icons/package";
    import { Button } from "$lib/components/ui/button/index";
    import * as Card from "$lib/components/ui/card/index.js";
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
    import { Input } from "$lib/components/ui/input/index";
    import { Label } from "$lib/components/ui/label/index";
    import * as Table from "$lib/components/ui/table/index.js";
    import type { Produto, ProdutoGrupo } from "$lib/types";
    import db, { queryHelper } from "@/db/db.svelte";
    import Ellipsis from "@lucide/svelte/icons/ellipsis";
    import PencilLine from "@lucide/svelte/icons/pencil-line";
    import Plus from "@lucide/svelte/icons/plus";
    import Search from "@lucide/svelte/icons/search";
    import Trash2 from "@lucide/svelte/icons/trash-2";
    import { onMount } from "svelte";
    import { toast } from "svelte-sonner";

    let produtos = $state<Array<Produto>>([]);
    let grupos = $state<Array<ProdutoGrupo>>([]);
    let dialog = $state<string | null>(null);
    let searchQuery = $state("");

    let filteredProdutos = $derived(
        produtos.filter(
            (p) =>
                p.descricao.toLowerCase().includes(searchQuery.toLowerCase()) ||
                p.codigo.toLowerCase().includes(searchQuery.toLowerCase()),
        ),
    );

    let produtoData = $state<Partial<Produto>>({
        codigo: "",
        descricao: "",
        grupo_id: 0,
        preco_compra: 0,
        preco_custo: 0,
        preco_venda: 0,
        preco_venda_b: 0,
        tabela_preco: "A",
        preco_minimo: 0,
    });

    // Pagination
    let currentPage = $state(1);
    const itemsPerPage = 20;
    let totalItems = $state(0);

    async function save() {
        try {
            const dataToSave = { ...produtoData };
            delete dataToSave.data_atualizacao;

            let q = queryHelper(dataToSave);
            let query = "";

            if (dataToSave.id) {
                query = `UPDATE produtos SET ${q.setClauses} WHERE id = ${dataToSave.id}`;
            } else {
                query = `INSERT INTO produtos (${q.columns}) VALUES (${q.placeholders})`;
            }

            await db.execute(query, q.values);

            await load();
            dialog = null;
            toast.success(
                `Produto ${dataToSave.id ? "atualizado" : "criado"} com sucesso!`,
            );
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            toast.error(`Falha ao salvar produto: ${message}`);
            console.error("Erro ao salvar produto:", e);
        }
    }

    async function delete_(id: number) {
        if (!confirm("Tem certeza que deseja excluir este produto?")) return;
        try {
            await db.execute("DELETE FROM produtos WHERE id = $1", [id]);
            await load();
            toast.success("Produto excluído com sucesso!");
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            toast.error(`Falha ao deletar produto: ${message}`);
            console.error("Erro ao deletar produto:", e);
        }
    }

    async function load() {
        try {
            const offset = (currentPage - 1) * itemsPerPage;

            const countRes = (await db.select(
                "SELECT COUNT(*) as count FROM produtos",
                [],
            )) as any;
            totalItems = countRes[0]?.count || 0;

            produtos = (await db.select(
                `
                SELECT p.*, (SELECT SUM(estoque_atual) FROM produto_variacoes WHERE produto_id = p.id) as estoque_atual
                FROM produtos p
                LIMIT $1 OFFSET $2
            `,
                [itemsPerPage, offset],
            )) as Array<Produto>;

            grupos = (await db.select(
                "SELECT * FROM produto_grupos",
                [],
            )) as Array<ProdutoGrupo>;
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            toast.error(`Falha ao carregar dados: ${message}`);
            console.error("Erro ao carregar dados:", e);
        }
    }

    onMount(() => load());

    $effect(() => {
        if (currentPage) load();
    });

    function resetProdutoData() {
        produtoData = {
            codigo: "",
            descricao: "",
            grupo_id: 0,
            preco_compra: 0,
            preco_custo: 0,
            preco_venda: 0,
            preco_venda_b: 0,
            tabela_preco: "A",
            preco_minimo: 0,
        };
    }
</script>

<Card.Root class="m-10">
    <Card.Header class="flex flex-row items-center">
        <div>
            <Card.Title class="text-3xl flex items-center gap-2">
                <Package class="h-8 w-8 text-primary" />
                Gerenciamento de Produtos
            </Card.Title>
            <Card.Description>
                Gerencie o catálogo de produtos e seus detalhes.
            </Card.Description>
        </div>
        <Button
            class="ml-auto cursor-pointer"
            variant="outline"
            size="lg"
            onclick={() => {
                resetProdutoData();
                dialog = "new";
            }}
        >
            Novo produto
            <Plus class="ml-2 h-4 w-4" />
        </Button>
    </Card.Header>
    <Card.Content>
        <div class="mb-6 flex items-center gap-4">
            <div class="relative flex-1 max-w-sm">
                <Search
                    class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"
                />
                <Input
                    type="search"
                    placeholder="Pesquisar por código ou descrição..."
                    class="pl-8"
                    bind:value={searchQuery}
                />
            </div>
        </div>

        <Table.Root>
            <Table.Header>
                <Table.Row>
                    <Table.Head>Código</Table.Head>
                    <Table.Head>Descrição</Table.Head>
                    <Table.Head>Grupo</Table.Head>
                    <Table.Head class="text-right">Preço Venda</Table.Head>
                    <Table.Head class="text-right">Estoque</Table.Head>
                    <Table.Head class="w-12.5"></Table.Head>
                </Table.Row>
            </Table.Header>
            <Table.Body>
                {#each filteredProdutos as produto (produto.id)}
                    <Table.Row>
                        <Table.Cell class="font-medium"
                            >{produto.codigo}</Table.Cell
                        >
                        <Table.Cell>{produto.descricao}</Table.Cell>
                        <Table.Cell>
                            {grupos.find((g) => g.id === produto.grupo_id)
                                ?.descricao || "N/A"}
                        </Table.Cell>
                        <Table.Cell class="text-right">
                            {produto.preco_venda?.toLocaleString("pt-BR", {
                                style: "currency",
                                currency: "BRL",
                            })}
                        </Table.Cell>
                        <Table.Cell class="text-right">
                            <!-- {/* Note: Estoque is handled via variations in the old project, but listed in the main table too */} -->
                            {produto.estoque_atual ?? "N/A"}
                        </Table.Cell>
                        <Table.Cell>
                            <Button
                                variant="ghost"
                                size="icon-lg"
                                onclick={() => {
                                    produtoData = { ...produto };
                                    dialog = "edit";
                                }}
                            >
                                <PencilLine
                                    class="h-4 w-4 stroke-3 stroke-lime-400"
                                />
                            </Button>
                            <Button
                                variant="ghost"
                                size="icon-lg"
                                onclick={() => delete_(produto.id)}
                            >
                                <Trash2
                                    class="h-4 w-4 stroke-3 stroke-red-500"
                                />
                            </Button>
                        </Table.Cell>
                    </Table.Row>
                {:else}
                    <Table.Row>
                        <Table.Cell
                            colspan={6}
                            class="text-center py-10 text-muted-foreground"
                        >
                            Nenhum produto encontrado com os filtros atuais.
                        </Table.Cell>
                    </Table.Row>
                {/each}
            </Table.Body>
        </Table.Root>

        <div class="flex items-center justify-end space-x-2 py-4">
            <Button
                variant="outline"
                size="sm"
                onclick={() => (currentPage = Math.max(currentPage - 1, 1))}
                disabled={currentPage === 1}
            >
                Anterior
            </Button>
            <div class="text-sm font-medium">
                Página {currentPage}
            </div>
            <Button
                variant="outline"
                size="sm"
                onclick={() => currentPage++}
                disabled={produtos.length < itemsPerPage}
            >
                Próxima
            </Button>
        </div>
    </Card.Content>
</Card.Root>

<Dialog.Root
    open={dialog != null}
    onOpenChange={(e) => {
        if (!e) {
            dialog = null;
        }
    }}
>
    <Dialog.Content class="sm:max-w-[600px]">
        <Dialog.Header>
            <Dialog.Title>
                {dialog === "new" ? "Novo Produto" : "Editar Produto"}
            </Dialog.Title>
            <Dialog.Description>
                Preencha as informações do produto abaixo.
            </Dialog.Description>
        </Dialog.Header>

        <div class="grid gap-4 py-4">
            <div class="grid grid-cols-2 gap-4">
                <div class="grid gap-2">
                    <Label for="codigo">Código</Label>
                    <Input id="codigo" bind:value={produtoData.codigo} />
                </div>
                <div class="grid gap-2">
                    <Label for="grupo">Grupo</Label>
                    <select
                        id="grupo"
                        class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                        bind:value={produtoData.grupo_id}
                    >
                        <option value={0}>Selecione um grupo</option>
                        {#each grupos as grupo}
                            <option value={grupo.id}>{grupo.descricao}</option>
                        {/each}
                    </select>
                </div>
            </div>

            <div class="grid gap-2">
                <Label for="descricao">Descrição</Label>
                <Input id="descricao" bind:value={produtoData.descricao} />
            </div>

            <div class="grid grid-cols-2 gap-4">
                <div class="grid gap-2">
                    <Label for="preco_compra">Preço Compra</Label>
                    <Input
                        id="preco_compra"
                        type="number"
                        step="0.01"
                        bind:value={produtoData.preco_compra}
                    />
                </div>
                <div class="grid gap-2">
                    <Label for="preco_custo">Preço Custo</Label>
                    <Input
                        id="preco_custo"
                        type="number"
                        step="0.01"
                        bind:value={produtoData.preco_custo}
                    />
                </div>
            </div>

            <div class="grid grid-cols-2 gap-4">
                <div class="grid gap-2">
                    <Label for="preco_venda">Preço Venda A</Label>
                    <Input
                        id="preco_venda"
                        type="number"
                        step="0.01"
                        bind:value={produtoData.preco_venda}
                    />
                </div>
                <div class="grid gap-2">
                    <Label for="preco_venda_b">Preço Venda B</Label>
                    <Input
                        id="preco_venda_b"
                        type="number"
                        step="0.01"
                        bind:value={produtoData.preco_venda_b}
                    />
                </div>
            </div>
        </div>

        <Dialog.Footer>
            <Button variant="outline" onclick={() => (dialog = null)}
                >Cancelar</Button
            >
            <Button onclick={save}>Salvar</Button>
        </Dialog.Footer>
    </Dialog.Content>
</Dialog.Root>

// src/pages/Produtos.tsx
import React, { useState, useEffect, useCallback } from "react";
import Modal from "../components/Modal";
import FiltroRoupasAvancado, {
    type FilterState,
} from "../components/FiltroRoupasAvancado";
import GradeTamanhosCores from "../components/GradeTamanhosCores";
import ComparadorProdutos from "../components/ComparadorProdutos";
import ClassificadorABC from "../components/ClassificadorABC";
import EditorEmMassa from "../components/EditorEmMassa";
import PageLayout from "../components/PageLayout";
import { useSeniorMode } from "../contexts/SeniorModeContext";

interface Tag {
    id: number;
    nome: string;
}

interface Variation {
    id?: number;
    sku: string;
    tamanho: string;
    cor: string;
    estoque_atual: number;
}

interface Produto {
    id?: number;
    codigo: string;
    descricao: string;
    grupo_id: number;
    preco_compra?: number; // NEW: Valor pago ao fornecedor
    preco_custo?: number; // Custo real (compra + margem do dono)
    preco_venda: number; // Tabela A (preço de venda padrão)
    preco_venda_b?: number; // NEW: Tabela B (vendedoras com maior margem)
    estoque_atual?: number;
    tabela_preco?: string;
    preco_minimo?: number;
    data_atualizacao?: string;
    tags?: Tag[];
    variations?: Variation[];
}

interface ProdutoGrupo {
    id: number;
    codigo: string;
    descricao: string;
}

const Produtos: React.FC = () => {
    const [produtos, setProdutos] = useState<Produto[]>([]);
    const [grupos, setGrupos] = useState<ProdutoGrupo[]>([]);
    const [mostrarForm, setMostrarForm] = useState(false);
    const [produtoEditando, setProdutoEditando] = useState<Produto | null>(
        null,
    );
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState<string | null>(null);
    const [filters, setFilters] = useState({});
    const [selectedProductIdForGrade, setSelectedProductIdForGrade] = useState<
        number | null
    >(null);

    const [showAdvancedTools, setShowAdvancedTools] = useState(false);
    const [activeTool, setActiveTool] = useState<string | null>(null);
    const { isSeniorMode } = useSeniorMode();

    // Pagination state
    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage] = useState(20);
    const [totalItems, setTotalItems] = useState(0);

    const carregarDados = useCallback(async () => {
        setLoading(true);
        setError(null);
        try {
            const queryParams = new URLSearchParams({
                ...(filters as Record<string, string>),
                page: currentPage.toString(),
                limit: itemsPerPage.toString(),
            }).toString();

            const produtosUrl = `http://localhost:3000/api/produtos?${queryParams}`;

            const [produtosResponse, gruposResponse] = await Promise.all([
                fetch(produtosUrl),
                fetch("http://localhost:3000/api/produto-grupos"),
            ]);

            if (!produtosResponse.ok) {
                throw new Error(
                    `HTTP error! status: ${produtosResponse.status} for produtos`,
                );
            }
            if (!gruposResponse.ok) {
                throw new Error(
                    `HTTP error! status: ${gruposResponse.status} for produto_grupos`,
                );
            }

            const produtosData = await produtosResponse.json();
            const gruposData: ProdutoGrupo[] = await gruposResponse.json();

            // Handle both paginated and non-paginated responses for backward compatibility
            const items = Array.isArray(produtosData)
                ? produtosData
                : produtosData.data || [];
            const total = Array.isArray(produtosData)
                ? produtosData.length
                : produtosData.total || 0;

            const processedProdutos = items.map((p: any) => ({
                ...p,
                preco_venda: p.preco_venda ? parseFloat(p.preco_venda) : 0,
                preco_custo: p.preco_custo
                    ? parseFloat(p.preco_custo)
                    : undefined,
                preco_minimo: p.preco_minimo
                    ? parseFloat(p.preco_minimo)
                    : undefined,
                estoque_atual: p.estoque_atual
                    ? parseFloat(p.estoque_atual)
                    : undefined,
            }));

            setProdutos(processedProdutos);
            setTotalItems(total);
            setGrupos(gruposData);
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            setError(`Falha ao carregar dados: ${message}`);
            console.error("Erro ao carregar dados:", e);
        } finally {
            setLoading(false);
        }
    }, [filters, currentPage, itemsPerPage]);

    useEffect(() => {
        carregarDados();
    }, [carregarDados]);

    const handleFilterChange = useCallback((newFilters: FilterState) => {
        setFilters(newFilters);
        setCurrentPage(1); // Reset to first page on filter change
    }, []);

    const salvarProduto = async (produto: Produto) => {
        setError(null);
        setSuccess(null);
        try {
            let response;
            if (produto.id) {
                response = await fetch(
                    `http://localhost:3000/api/produtos/${produto.id}`,
                    {
                        method: "PUT",
                        headers: { "Content-Type": "application/json" },
                        body: JSON.stringify(produto),
                    },
                );
            } else {
                response = await fetch("http://localhost:3000/api/produtos", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify(produto),
                });
            }

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            await carregarDados();
            setMostrarForm(false);
            setProdutoEditando(null);
            setSuccess(
                `Produto ${produto.id ? "atualizado" : "criado"} com sucesso!`,
            );
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            setError(`Falha ao salvar produto: ${message}`);
            console.error("Erro ao salvar produto:", e);
        }
    };

    const deletarProduto = async (id: number) => {
        if (!window.confirm("Confirmar exclusão?")) {
            return;
        }
        setError(null);
        setSuccess(null);
        try {
            const response = await fetch(
                `http://localhost:3000/api/produtos/${id}`,
                {
                    method: "DELETE",
                },
            );

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            await carregarDados();
            setSuccess("Produto excluído com sucesso!");
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            setError(`Falha ao deletar produto: ${message}`);
            console.error("Erro ao deletar produto:", e);
        }
    };

    const handleToolToggle = (tool: string) => {
        if (activeTool === tool) {
            setActiveTool(null);
        } else {
            setActiveTool(tool);
        }
    };

    if (selectedProductIdForGrade) {
        return (
            <PageLayout title="Grade de Tamanhos e Cores">
                <button
                    onClick={() => setSelectedProductIdForGrade(null)}
                    className="mb-4 bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-md transition-colors"
                >
                    ← Voltar para Produtos
                </button>
                <GradeTamanhosCores productId={selectedProductIdForGrade} />
            </PageLayout>
        );
    }

    const actions = (
        <div className="flex gap-4">
            <button
                onClick={() => {
                    setProdutoEditando(null);
                    setMostrarForm(true);
                    setActiveTool(null);
                }}
                className={`${isSeniorMode ? "bg-blue-600 hover:bg-blue-700 py-3 px-6 text-xl" : "bg-blue-500 hover:bg-blue-600 py-2 px-4"} text-white font-bold rounded-md transition-colors`}
            >
                {isSeniorMode ? "+ Adicionar Novo Produto" : "+ Novo Produto"}
            </button>
            {!isSeniorMode && (
                <button
                    onClick={() => setShowAdvancedTools(!showAdvancedTools)}
                    className="bg-gray-200 hover:bg-gray-300 text-gray-800 font-bold py-2 px-4 rounded-md transition-colors"
                >
                    {showAdvancedTools
                        ? "Ocultar Ferramentas"
                        : "Ferramentas Avançadas"}
                </button>
            )}
        </div>
    );

    return (
        <PageLayout
            title="Gerenciar Produtos"
            actions={actions}
            isLoading={loading}
            error={error}
            success={success}
            onErrorClose={() => setError(null)}
            onSuccessClose={() => setSuccess(null)}
        >
            {showAdvancedTools && !isSeniorMode && (
                <div className="advanced-tools bg-gray-50 p-4 rounded-lg mb-6 border">
                    <h3 className="text-lg font-semibold mb-4">
                        Ferramentas Avançadas
                    </h3>
                    <div className="flex space-x-4 mb-4">
                        <button
                            onClick={() => handleToolToggle("mass_editor")}
                            className={`font-bold py-2 px-4 rounded-md transition-colors ${activeTool === "mass_editor" ? "bg-orange-500 text-white" : "bg-orange-200 hover:bg-orange-300 text-orange-800"}`}
                        >
                            Editor em Massa
                        </button>
                        <button
                            onClick={() => handleToolToggle("abc_analysis")}
                            className={`font-bold py-2 px-4 rounded-md transition-colors ${activeTool === "abc_analysis" ? "bg-green-500 text-white" : "bg-green-200 hover:bg-green-300 text-green-800"}`}
                        >
                            Análise ABC
                        </button>
                        <button
                            onClick={() =>
                                handleToolToggle("product_comparator")
                            }
                            className={`font-bold py-2 px-4 rounded-md transition-colors ${activeTool === "product_comparator" ? "bg-purple-500 text-white" : "bg-purple-200 hover:bg-purple-300 text-purple-800"}`}
                        >
                            Comparar Produtos
                        </button>
                    </div>

                    {activeTool === "mass_editor" && <EditorEmMassa />}
                    {activeTool === "abc_analysis" && <ClassificadorABC />}
                    {activeTool === "product_comparator" && (
                        <ComparadorProdutos />
                    )}

                    <h3 className="text-lg font-semibold mb-4 mt-6">
                        Filtros Avançados
                    </h3>
                    <FiltroRoupasAvancado onFilterChange={handleFilterChange} />
                </div>
            )}

            <Modal
                isOpen={mostrarForm}
                onClose={() => {
                    setMostrarForm(false);
                    setProdutoEditando(null);
                }}
                size="4xl"
            >
                <ProdutoForm
                    produto={produtoEditando}
                    grupos={grupos}
                    onSave={salvarProduto}
                    onCancel={() => {
                        setMostrarForm(false);
                        setProdutoEditando(null);
                    }}
                />
            </Modal>

            <div className="table-container overflow-x-auto">
                <table
                    className={`min-w-full bg-white border border-gray-200 ${isSeniorMode ? "text-lg" : "text-sm"}`}
                >
                    <thead>
                        <tr className="bg-gray-100 border-b">
                            <th className="py-3 px-4 text-left font-semibold text-gray-600">
                                Código
                            </th>
                            <th className="py-3 px-4 text-left font-semibold text-gray-600">
                                Descrição
                            </th>
                            <th className="py-3 px-4 text-left font-semibold text-gray-600">
                                Grupo
                            </th>
                            <th className="py-3 px-4 text-left font-semibold text-gray-600">
                                Preço Venda
                            </th>
                            <th className="py-3 px-4 text-left font-semibold text-gray-600">
                                Estoque
                            </th>
                            <th className="py-3 px-4 text-left font-semibold text-gray-600">
                                Ações
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {produtos.map((produto) => (
                            <tr
                                key={produto.id}
                                className="border-b hover:bg-gray-50"
                            >
                                <td className="py-3 px-4 text-gray-700">
                                    {produto.codigo}
                                </td>
                                <td className="py-3 px-4 text-gray-700">
                                    {produto.descricao}
                                </td>
                                <td className="py-3 px-4 text-gray-700">
                                    {grupos.find(
                                        (g) => g.id === produto.grupo_id,
                                    )?.descricao || "N/A"}
                                </td>
                                <td className="py-3 px-4 text-gray-700">
                                    {produto.preco_venda}
                                </td>
                                <td className="py-3 px-4 text-gray-700">
                                    {produto.estoque_atual != null
                                        ? produto.estoque_atual
                                        : "N/A"}
                                </td>
                                <td className="py-3 px-4">
                                    {!isSeniorMode && (
                                        <button
                                            onClick={() => {
                                                setSelectedProductIdForGrade(
                                                    produto.id!,
                                                );
                                            }}
                                            className="bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-1 px-3 rounded-md mr-2 transition-colors"
                                        >
                                            Grade
                                        </button>
                                    )}
                                    <button
                                        onClick={() => {
                                            setProdutoEditando(produto);
                                            setMostrarForm(true);
                                        }}
                                        className={`${isSeniorMode ? "py-2 px-4 text-lg" : "py-1 px-3"} bg-yellow-500 hover:bg-yellow-600 text-white font-bold rounded-md mr-2 transition-colors`}
                                    >
                                        Editar
                                    </button>
                                    <button
                                        onClick={() =>
                                            deletarProduto(produto.id!)
                                        }
                                        className={`${isSeniorMode ? "py-2 px-4 text-lg" : "py-1 px-3"} bg-red-500 hover:bg-red-600 text-white font-bold rounded-md transition-colors`}
                                    >
                                        Excluir
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Pagination Controls */}
            <div className="flex justify-center mt-6 gap-2">
                <button
                    onClick={() =>
                        setCurrentPage((prev) => Math.max(prev - 1, 1))
                    }
                    disabled={currentPage === 1}
                    className={`px-4 py-2 rounded ${currentPage === 1 ? "bg-gray-200 text-gray-400" : "bg-blue-500 text-white hover:bg-blue-600"}`}
                >
                    Anterior
                </button>
                <span className="px-4 py-2 text-gray-700">
                    Página {currentPage}
                </span>
                <button
                    onClick={() => setCurrentPage((prev) => prev + 1)}
                    disabled={
                        produtos.length < itemsPerPage ||
                        currentPage * itemsPerPage >= totalItems
                    }
                    className={`px-4 py-2 rounded ${produtos.length < itemsPerPage || currentPage * itemsPerPage >= totalItems ? "bg-gray-200 text-gray-400" : "bg-blue-500 text-white hover:bg-blue-600"}`}
                >
                    Próxima
                </button>
            </div>
        </PageLayout>
    );
};

export default Produtos;

const ProdutoForm: React.FC<{
    produto: Produto | null;
    grupos: ProdutoGrupo[];
    onSave: (produto: Produto) => void;
    onCancel: () => void;
}> = ({ produto, grupos, onSave, onCancel }) => {
    const { isSeniorMode } = useSeniorMode();
    const [formData, setFormData] = useState<Produto>(
        produto || {
            codigo: "",
            descricao: "",
            grupo_id: 0,
            preco_compra: 0,
            preco_custo: 0,
            preco_venda: 0,
            preco_venda_b: 0,
            tabela_preco: "A",
            preco_minimo: 0,
        },
    );

    useEffect(() => {
        setFormData(
            produto || {
                codigo: "",
                descricao: "",
                grupo_id: 0,
                preco_compra: 0,
                preco_custo: 0,
                preco_venda: 0,
                preco_venda_b: 0,
                tabela_preco: "A",
                preco_minimo: 0,
            },
        );
    }, [produto]);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave(formData);
    };

    return (
        <div
            className={`w-full bg-white shadow-2xl rounded-2xl ${isSeniorMode ? "p-8" : "p-10"}`}
        >
            <h2
                className={`${isSeniorMode ? "text-5xl mb-8" : "text-4xl mb-4"} font-bold text-gray-800 text-center`}
            >
                {produto ? "Editar" : "Novo"} Produto
            </h2>
            <form onSubmit={handleSubmit} className="space-y-8">
                <div>
                    <label
                        className={`block font-semibold text-gray-700 mb-2 ${isSeniorMode ? "text-2xl" : "text-xl"}`}
                    >
                        Informações Básicas
                    </label>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <input
                            type="text"
                            placeholder="Código"
                            value={formData.codigo}
                            onChange={(e) =>
                                setFormData({
                                    ...formData,
                                    codigo: e.target.value,
                                })
                            }
                            required
                            className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? "py-4 px-6 text-2xl" : "py-3 px-4 text-lg"}`}
                        />
                        <input
                            type="text"
                            placeholder="Descrição"
                            value={formData.descricao}
                            onChange={(e) =>
                                setFormData({
                                    ...formData,
                                    descricao: e.target.value,
                                })
                            }
                            required
                            className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? "py-4 px-6 text-2xl" : "py-3 px-4 text-lg"}`}
                        />
                        <select
                            value={formData.grupo_id}
                            onChange={(e) =>
                                setFormData({
                                    ...formData,
                                    grupo_id: parseInt(e.target.value),
                                })
                            }
                            required
                            className={`shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${isSeniorMode ? "py-4 px-6 text-2xl" : "py-3 px-4 text-lg"}`}
                        >
                            <option value="">Selecione um Grupo</option>
                            {grupos.map((grupo) => (
                                <option key={grupo.id} value={grupo.id}>
                                    {grupo.descricao}
                                </option>
                            ))}
                        </select>
                    </div>
                </div>

                <div>
                    <label
                        className={`block font-semibold text-gray-700 mb-2 ${isSeniorMode ? "text-2xl" : "text-xl"}`}
                    >
                        Preços
                    </label>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        <div>
                            <label className="block text-sm text-gray-500 mb-1">
                                Preço Compra
                            </label>
                            <input
                                type="number"
                                placeholder="0.00"
                                value={formData.preco_compra || ""}
                                onChange={(e) =>
                                    setFormData({
                                        ...formData,
                                        preco_compra: parseFloat(
                                            e.target.value,
                                        ),
                                    })
                                }
                                step="0.01"
                                className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            />
                        </div>
                        <div>
                            <label className="block text-sm text-gray-500 mb-1">
                                Preço Custo
                            </label>
                            <input
                                type="number"
                                placeholder="0.00"
                                value={formData.preco_custo || ""}
                                onChange={(e) =>
                                    setFormData({
                                        ...formData,
                                        preco_custo: parseFloat(e.target.value),
                                    })
                                }
                                step="0.01"
                                className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            />
                        </div>
                        <div>
                            <label className="block text-sm text-gray-500 mb-1">
                                Venda A (Padrão)
                            </label>
                            <input
                                type="number"
                                placeholder="0.00"
                                value={formData.preco_venda}
                                onChange={(e) =>
                                    setFormData({
                                        ...formData,
                                        preco_venda: parseFloat(e.target.value),
                                    })
                                }
                                step="0.01"
                                required
                                className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                            />
                        </div>
                        <div>
                            <label className="block text-sm text-gray-500 mb-1">
                                Venda B (Margem Maior)
                            </label>
                            <input
                                type="number"
                                placeholder="0.00"
                                value={formData.preco_venda_b || ""}
                                onChange={(e) =>
                                    setFormData({
                                        ...formData,
                                        preco_venda_b: parseFloat(
                                            e.target.value,
                                        ),
                                    })
                                }
                                step="0.01"
                                className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                            />
                        </div>
                    </div>
                </div>

                <div className="form-actions flex justify-center gap-6 pt-4">
                    <button
                        type="button"
                        onClick={onCancel}
                        className={`w-1/3 bg-gray-500 hover:bg-gray-600 text-white font-bold rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300 ${isSeniorMode ? "py-6 px-10 text-2xl" : "py-4 px-8 text-xl"}`}
                    >
                        Cancelar
                    </button>
                    <button
                        type="submit"
                        className={`w-1/3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300 ${isSeniorMode ? "py-6 px-10 text-2xl" : "py-4 px-8 text-xl"}`}
                    >
                        {isSeniorMode ? "Salvar Produto" : "Salvar"}
                    </button>
                </div>
            </form>
        </div>
    );
};
