// src/routes/rotas/+page.svelte
<script lang="ts">
  import Route from "@lucide/svelte/icons/route";
  import * as Card from "$lib/components/ui/card/index.js";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
  import * as Table from "$lib/components/ui/table/index.js";
  import { Button } from "@/components/ui/button/index";
  import { Input } from "@/components/ui/input/index";
  import { Label } from "@/components/ui/label/index";
  import db, { queryHelper } from "@/db/db.svelte";
  import type { Praca, Rota } from "@/types";
  import Ellipsis from "@lucide/svelte/icons/ellipsis";
  import PencilLine from "@lucide/svelte/icons/pencil-line";
  import Plus from "@lucide/svelte/icons/plus";
  import Trash2 from "@lucide/svelte/icons/trash-2";
  import { onMount } from "svelte";
  import { toast } from "svelte-sonner";

  let routes = $state<Array<Rota>>([]);
  let pracas = $state<Array<Praca>>([]);
  let dialog = $state<string | null>(null);

  let routeData = $state<Partial<Rota>>({
    codigo: "",
    nome: "",
    bairro: "",
    praca_id: 0,
  });

  async function save() {
    try {
      const dataToSave = { ...routeData };
      delete (dataToSave as any).data_cadastro;

      let q = queryHelper(dataToSave);
      let query = "";

      if (dataToSave.id) {
        query = `UPDATE rotas SET ${q.setClauses} WHERE id = ${dataToSave.id}`;
      } else {
        query = `INSERT INTO rotas (${q.columns}) VALUES (${q.placeholders})`;
      }

      await db.execute(query, q.values);

      await load();
      dialog = null;
      toast.success(
        `Rota ${dataToSave.id ? "atualizada" : "criada"} com sucesso!`
      );
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      toast.error(`Falha ao salvar rota: ${message}`);
      console.error("Erro ao salvar rota:", e);
    }
  }

  async function delete_(id: number) {
    try {
      await db.execute("DELETE FROM rotas WHERE id = $1", [id]);
      await load();
      toast.success("Rota excluído com sucesso!");
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      toast.error(`Falha ao deletar rota: ${message}`);
      console.error("Erro ao deletar rota:", e);
    }
  }

  async function load() {
    try {
      routes = (await db.select("SELECT * FROM rotas", [])) as Array<Rota>;
      pracas = (await db.select("SELECT * FROM pracas", [])) as Array<Praca>;
    } catch (e: unknown) {
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      toast.error(`Falha ao carregar rotas: ${message}`);
      console.error("Erro ao carregar rotas:", e);
    }
  }

  onMount(() => load());
</script>

<Card.Root class="m-10">
  <Card.Header class="flex w-full">
    <Card.Title class="text-3xl flex items-center gap-2">
      <Route class="h-8 w-8 text-primary" />
      Gerenciamento de Rotas
    </Card.Title>
    <Button
      class="ml-auto cursor-pointer"
      variant="outline"
      size="lg"
      onclick={() => {
        dialog = "new";
      }}
    >
      Nova rota
      <Plus class="stroke-2" />
    </Button>
  </Card.Header>
  <Card.Content>
    <Table.Root>
      <Table.Caption>Lista de vendedores.</Table.Caption>
      <Table.Header>
        <Table.Row>
          <Table.Head>Código</Table.Head>
          <Table.Head>Praça</Table.Head>
          <Table.Head>Bairro</Table.Head>
          <Table.Head>Nome</Table.Head>
          <Table.Head class="w-12.5"></Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#each routes as route, i (route.id)}
          <Table.Row>
            <Table.Cell>{route.codigo}</Table.Cell>
            <Table.Cell class="text-primary">
              {pracas.find((p) => p.id === route.praca_id)?.nome || "N/A"}
            </Table.Cell>
            <Table.Cell>{route.bairro}</Table.Cell>
            <Table.Cell>{route.nome}</Table.Cell>
            <Table.Cell>
              <Button
                variant="ghost"
                size="icon-lg"
                onclick={() => {
                  routeData = { ...route };
                  dialog = "edit";
                }}
              >
                <PencilLine class="h-4 w-4 stroke-3 stroke-lime-400" />
              </Button>
              <Button
                variant="ghost"
                size="icon-lg"
                onclick={() => delete_(route.id)}
              >
                <Trash2 class="h-4 w-4 stroke-3 stroke-red-500" />
              </Button>
            </Table.Cell>
          </Table.Row>
        {/each}
      </Table.Body>
    </Table.Root>
  </Card.Content>
</Card.Root>

<Dialog.Root
  open={dialog != null}
  onOpenChange={(e) =>
    e
      ? null
      : ((dialog = null),
        (routeData = { codigo: "", nome: "", bairro: "", praca_id: 0 }))}
>
  <Dialog.Content class="gap-10">
    <Dialog.Header>
      <Dialog.Title>
        {#if dialog == "new"}
          Nova rota
        {:else if dialog == "edit"}
          Editar rota
        {/if}
      </Dialog.Title>
    </Dialog.Header>

    <div class="flex flex-col gap-5">
      <div class="flex flex-col gap-3">
        <Label for="code">Codigo:</Label>
        <Input id="code" bind:value={routeData.codigo} placeholder="R001..." />
      </div>
      <div class="flex flex-col gap-3">
        <Label for="praca">Praça:</Label>
        <select
          id="praca"
          bind:value={routeData.praca_id}
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          required
        >
          <option value={0}>Selecione uma praça...</option>
          {#each pracas as p}
            <option value={p.id}>{p.codigo} - {p.nome}</option>
          {/each}
        </select>
      </div>
      <div class="flex flex-col gap-3">
        <Label for="name">Nome:</Label>
        <Input id="name" bind:value={routeData.nome} placeholder="..." />
      </div>

      <div class="flex flex-col gap-3">
        <Label for="email">Bairro:</Label>
        <Input id="email" bind:value={routeData.bairro} placeholder="..." />
      </div>
    </div>

    <Dialog.Footer class="grid grid-cols-2 gap-5">
      <Button variant="outline" onclick={() => (dialog = null)}>
        Cancelar
      </Button>
      <Button onclick={save}>Salvar</Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

// src/pages/Rotas.tsx
import React, { useState, useEffect } from 'react';
import Modal from '../components/Modal';
import Alerta from '../components/Alerta'; // Import Alerta

interface Rota {
  id?: number; // ID is optional for new entries
  codigo: string;
  bairro?: string;
  nome?: string;
}

const Rotas: React.FC = () => {
  const [rotas, setRotas] = useState<Rota[]>([]);
  const [mostrarForm, setMostrarForm] = useState(false);
  const [rotaEditando, setRotaEditando] = useState<Rota | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null); // Add success state

  useEffect(() => {
    carregarRotas();
  }, []);

  const carregarRotas = async () => {
    setLoading(true);
    setError(null);
    // Do not reset success here so message can persist after reload
    try {
      const response = await fetch('http://localhost:3000/api/rotas');
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data: Rota[] = await response.json();
      setRotas(data);
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao carregar rotas: ${message}`);
      console.error("Erro ao carregar rotas:", e);
    } finally {
      setLoading(false);
    }
  };

  const salvarRota = async (rota: Rota) => {
    setError(null);
    setSuccess(null); // Reset success message
    try {
      let response;
      if (rota.id) {
        // Update existing rota
        response = await fetch(`http://localhost:3000/api/rotas/${rota.id}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(rota),
        });
      } else {
        // Create new rota
        response = await fetch('http://localhost:3000/api/rotas', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(rota),
        });
      }

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarRotas(); // Reload rotas after save
      setMostrarForm(false);
      setRotaEditando(null);
      setSuccess(`Rota ${rota.id ? 'atualizada' : 'criada'} com sucesso!`); // Set success message
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao salvar rota: ${message}`);
      console.error("Erro ao salvar rota:", e);
    }
  };

  const deletarRota = async (id: number) => {
    if (!window.confirm('Confirmar exclusão?')) {
      return;
    }
    setError(null);
    setSuccess(null); // Reset success message
    try {
      const response = await fetch(`http://localhost:3000/api/rotas/${id}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarRotas(); // Reload rotas after delete
      setSuccess("Rota excluída com sucesso!"); // Set success message
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao deletar rota: ${message}`);
      console.error("Erro ao deletar rota:", e);
    }
  };

  if (loading) {
    return <div className="text-center p-6">Carregando rotas...</div>;
  }

  // Error display from the initial load should still show.
  // The Alerta component will handle subsequent errors from save/delete.

  return (
    <div className="page-container p-6 bg-white shadow-md rounded-lg">
      
      {/* Display Alerta for success and error messages */}
      {success && <Alerta message={success} onClose={() => setSuccess(null)} />}
      {error && <Alerta message={error} onClose={() => setError(null)} />}

      <div className="page-header flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-800">Gerenciar Rotas</h1>
        <button 
          onClick={() => { setRotaEditando(null); setMostrarForm(true); }}
          className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition-colors"
        >
          + Nova Rota
        </button>
      </div>

      <Modal isOpen={mostrarForm} onClose={() => { setMostrarForm(false); setRotaEditando(null); }}>
        <RotaForm
          rota={rotaEditando}
          onSave={salvarRota}
          onCancel={() => { setMostrarForm(false); setRotaEditando(null); }}
        />
      </Modal>

      <div className="table-container overflow-x-auto">
        <table className="min-w-full bg-white border border-gray-200">
          <thead>
            <tr className="bg-gray-100 border-b">
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Código</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Bairro</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Nome</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Ações</th>
            </tr>
          </thead>
          <tbody>
            {rotas.map(rota => (
              <tr key={rota.id} className="border-b hover:bg-gray-50">
                <td className="py-3 px-4 text-sm text-gray-700">{rota.codigo}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{rota.bairro}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{rota.nome}</td>
                <td className="py-3 px-4 text-sm">
                  <button 
                    onClick={() => { setRotaEditando(rota); setMostrarForm(true); }}
                    className="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-3 rounded-md mr-2 transition-colors"
                  >
                    Editar
                  </button>
                  <button 
                    onClick={() => deletarRota(rota.id!)}
                    className="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-3 rounded-md transition-colors"
                  >
                    Excluir
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

const RotaForm: React.FC<{
  rota: Rota | null;
  onSave: (rota: Rota) => void;
  onCancel: () => void;
}> = ({ rota, onSave, onCancel }) => {
  const [formData, setFormData] = useState<Rota>(
    rota || {
      codigo: '',
      bairro: '',
      nome: '',
    }
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <div className="max-w-4xl w-full bg-white shadow-2xl rounded-2xl p-10">
        <h2 className="text-4xl font-bold text-gray-800 text-center mb-4">
            {rota ? 'Editar' : 'Nova'} Rota
        </h2>
        <p className="text-center text-gray-600 mb-8 text-lg">
            Preencha os dados para {rota ? 'atualizar a' : 'criar uma nova'} rota.
        </p>
      <form onSubmit={handleSubmit} className="space-y-8">
        <div>
            <label className="block text-xl font-semibold text-gray-700 mb-2">
                1. Informações da Rota
            </label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <input
                    type="text"
                    placeholder="Código"
                    value={formData.codigo}
                    onChange={e => setFormData({ ...formData, codigo: e.target.value })}
                    required
                    className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                <input
                    type="text"
                    placeholder="Nome"
                    value={formData.nome || ''}
                    onChange={e => setFormData({ ...formData, nome: e.target.value })}
                    className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
            </div>
        </div>

        <div>
            <label htmlFor="bairro" className="block text-xl font-semibold text-gray-700 mb-2">
                2. Bairro
            </label>
            <input
                type="text"
                id="bairro"
                placeholder="Bairro"
                value={formData.bairro || ''}
                onChange={e => setFormData({ ...formData, bairro: e.target.value })}
                className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
        </div>

        <div className="form-actions flex justify-center gap-6 pt-4">
            <button
                type="button"
                onClick={onCancel}
                className="w-1/3 bg-gray-500 hover:bg-gray-600 text-white font-bold text-xl py-4 px-8 rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300"
            >
                Cancelar
            </button>
            <button
                type="submit"
                className="w-1/3 bg-green-600 hover:bg-green-700 text-white font-bold text-xl py-4 px-8 rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300"
            >
                Salvar
            </button>
        </div>
      </form>
    </div>
  );
};
  
  export default Rotas;
