// src/routes/solicitacoes/+page.svelte
<script lang="ts">
  import FileText from "@lucide/svelte/icons/file-text";
  import * as Card from "$lib/components/ui/card/index.js";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import * as Table from "$lib/components/ui/table/index.js";
  import { Button } from "$lib/components/ui/button/index";
  import { Input } from "$lib/components/ui/input/index";
  import { Label } from "@/components/ui/label/index";
  import db, { queryHelper } from "@/db/db.svelte";
  import type { Solicitacao, Vendedor, Cliente } from "$lib/types";
  import Plus from "@lucide/svelte/icons/plus";
  import PencilLine from "@lucide/svelte/icons/pencil-line";
  import Trash2 from "@lucide/svelte/icons/trash-2";
  import Search from "@lucide/svelte/icons/search";
  import { onMount } from "svelte";
  import { toast } from "svelte-sonner";

  let solicitacoes = $state<Array<Solicitacao>>([]);
  let vendedores = $state<Array<Vendedor>>([]);
  let clientes = $state<Array<Cliente>>([]);
  let dialog = $state<string | null>(null);
  let searchQuery = $state("");

  let filteredSolicitacoes = $derived(
    solicitacoes.filter(
      (s) =>
        s.numero.toLowerCase().includes(searchQuery.toLowerCase()) ||
        clientes
          .find((c) => c.id === s.cliente_id)
          ?.nome.toLowerCase()
          .includes(searchQuery.toLowerCase())
    )
  );

  let solicitacaoData = $state<Partial<Solicitacao>>({
    numero: "",
    vendedor_id: 0,
    cliente_id: 0,
    data_solicitacao: new Date().toISOString().split("T")[0] as any,
    situacao: "Pendente",
  });

  async function save() {
    try {
      const dataToSave = { ...solicitacaoData };
      delete (dataToSave as any).data_cadastro;

      let q = queryHelper(dataToSave);
      let query = "";

      if (dataToSave.id) {
        query = `UPDATE solicitacoes SET ${q.setClauses} WHERE id = ${dataToSave.id}`;
      } else {
        query = `INSERT INTO solicitacoes (${q.columns}) VALUES (${q.placeholders})`;
      }

      await db.execute(query, q.values);

      await load();
      dialog = null;
      toast.success(
        `Solicitação ${dataToSave.id ? "atualizada" : "criada"} com sucesso!`
      );
    } catch (e: any) {
      toast.error(e.message || "Erro ao salvar solicitação");
      console.error(e);
    }
  }

  async function delete_(id: number) {
    if (!confirm("Confirmar exclusão?")) return;
    try {
      await db.execute("DELETE FROM solicitacoes WHERE id = $1", [id]);
      await load();
      toast.success("Solicitação excluída com sucesso!");
    } catch (e: any) {
      toast.error(e.message || "Erro ao excluir solicitação");
      console.error(e);
    }
  }

  async function load() {
    try {
      solicitacoes = (await db.select(
        "SELECT * FROM solicitacoes",
        []
      )) as Array<Solicitacao>;
      vendedores = (await db.select(
        "SELECT * FROM vendedores",
        []
      )) as Array<Vendedor>;
      clientes = (await db.select(
        "SELECT * FROM clientes",
        []
      )) as Array<Cliente>;
    } catch (e: any) {
      console.error(e);
      toast.error("Erro ao carregar dados do banco de dados.");
    }
  }

  onMount(() => load());

  function resetData() {
    solicitacaoData = {
      numero: "",
      vendedor_id: 0,
      cliente_id: 0,
      data_solicitacao: new Date().toISOString().split("T")[0] as any,
      situacao: "Pendente",
    };
  }
</script>

<Card.Root class="m-10">
  <Card.Header class="flex flex-row items-center">
    <div>
      <Card.Title class="text-3xl flex items-center gap-2">
        <FileText class="h-8 w-8 text-primary" />
        Gerenciamento de Solicitações
      </Card.Title>
      <Card.Description>
        Gerencie as solicitações de clientes e vendedores.
      </Card.Description>
    </div>
    <Button
      class="ml-auto cursor-pointer"
      variant="outline"
      size="lg"
      onclick={() => {
        resetData();
        dialog = "new";
      }}
    >
      Nova solicitação
      <Plus class="ml-2 h-4 w-4" />
    </Button>
  </Card.Header>
  <Card.Content>
    <div class="mb-6 flex items-center gap-4">
      <div class="relative flex-1 max-w-sm">
        <Search
          class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"
        />
        <Input
          type="search"
          placeholder="Pesquisar por número ou cliente..."
          class="pl-8"
          bind:value={searchQuery}
        />
      </div>
    </div>

    <Table.Root>
      <Table.Header>
        <Table.Row>
          <Table.Head>Número</Table.Head>
          <Table.Head>Vendedor</Table.Head>
          <Table.Head>Cliente</Table.Head>
          <Table.Head>Data</Table.Head>
          <Table.Head>Situação</Table.Head>
          <Table.Head class="w-12.5"></Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#each filteredSolicitacoes as sol (sol.id)}
          <Table.Row>
            <Table.Cell class="font-medium text-primary">
              {sol.numero}
            </Table.Cell>
            <Table.Cell>
              {vendedores.find((v) => v.id === sol.vendedor_id)?.nome || "—"}
            </Table.Cell>
            <Table.Cell>
              {clientes.find((c) => c.id === sol.cliente_id)?.nome || "—"}
            </Table.Cell>
            <Table.Cell>
              {new Date(sol.data_solicitacao).toLocaleDateString("pt-BR")}
            </Table.Cell>
            <Table.Cell>
              <span
                class="px-2 py-1 rounded-full text-xs font-semibold bg-primary/10 text-primary"
              >
                {sol.situacao || "Pendente"}
              </span>
            </Table.Cell>
            <Table.Cell class="flex justify-end gap-2">
              <Button
                variant="ghost"
                size="icon-lg"
                onclick={() => {
                  solicitacaoData = sol;
                  dialog = "edit";
                }}
              >
                <PencilLine class="h-4 w-4 stroke-3 stroke-lime-400" />
              </Button>
              <Button
                variant="ghost"
                size="icon-lg"
                onclick={() => delete_(sol.id!)}
              >
                <Trash2 class="h-4 w-4 stroke-3 stroke-red-500" />
              </Button>
            </Table.Cell>
          </Table.Row>
        {:else}
          <Table.Row>
            <Table.Cell
              colspan={6}
              class="text-center py-10 text-muted-foreground"
            >
              Nenhuma solicitação encontrada.
            </Table.Cell>
          </Table.Row>
        {/each}
      </Table.Body>
    </Table.Root>
  </Card.Content>
</Card.Root>

<Dialog.Root open={dialog != null} onOpenChange={(e) => !e && (dialog = null)}>
  <Dialog.Content class="sm:max-w-[425px]">
    <Dialog.Header>
      <Dialog.Title
        >{dialog === "new"
          ? "Nova Solicitação"
          : "Editar Solicitação"}</Dialog.Title
      >
      <Dialog.Description
        >Preencha os campos abaixo para salvar a solicitação.</Dialog.Description
      >
    </Dialog.Header>
    <div class="grid gap-4 py-4">
      <div class="grid gap-2">
        <Label for="numero">Número</Label>
        <Input
          id="numero"
          bind:value={solicitacaoData.numero}
          placeholder="Ex: SOL-001"
        />
      </div>
      <div class="grid gap-2">
        <Label for="data">Data</Label>
        <Input
          id="data"
          type="date"
          bind:value={solicitacaoData.data_solicitacao}
        />
      </div>
      <div class="grid gap-2">
        <Label for="vendedor">Vendedor</Label>
        <select
          id="vendedor"
          bind:value={solicitacaoData.vendedor_id}
          class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
        >
          <option value={0}>Selecione um vendedor...</option>
          {#each vendedores as v}
            <option value={v.id}>{v.nome}</option>
          {/each}
        </select>
      </div>
      <div class="grid gap-2">
        <Label for="cliente">Cliente</Label>
        <select
          id="cliente"
          bind:value={solicitacaoData.cliente_id}
          class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
        >
          <option value={0}>Selecione um cliente...</option>
          {#each clientes as c}
            <option value={c.id}>{c.nome}</option>
          {/each}
        </select>
      </div>
      <div class="grid gap-2">
        <Label for="situacao">Situação</Label>
        <Input
          id="situacao"
          bind:value={solicitacaoData.situacao}
          placeholder="Ex: Pendente, Aprovada..."
        />
      </div>
    </div>
    <Dialog.Footer>
      <Button variant="outline" onclick={() => (dialog = null)}>Cancelar</Button
      >
      <Button onclick={save}>Salvar</Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

// src/pages/Solicitacoes.tsx
import React, { useState, useEffect } from 'react';
import Modal from '../components/Modal';
import Alerta from '../components/Alerta';

interface Solicitacao {
  id?: number; // ID is optional for new entries
  numero: string;
  vendedor_id: number;
  cliente_id: number;
  data_solicitacao: string; // DATE type
  situacao?: string;
}

interface Vendedor {
  id: number;
  nome: string;
}

interface Cliente {
  id: number;
  nome: string;
}

const Solicitacoes: React.FC = () => {
  const [solicitacoes, setSolicitacoes] = useState<Solicitacao[]>([]);
  const [vendedores, setVendedores] = useState<Vendedor[]>([]);
  const [clientes, setClientes] = useState<Cliente[]>([]);
  const [mostrarForm, setMostrarForm] = useState(false);
  const [solicitacaoEditando, setSolicitacaoEditando] = useState<Solicitacao | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null); // Add success state

  useEffect(() => {
    carregarDados();
  }, []);

  const carregarDados = async () => {
    setLoading(true);
    setError(null);
    // Do not reset success here so message can persist after reload
    try {
      const [solicitacoesResponse, vendedoresResponse, clientesResponse] = await Promise.all([
        fetch('http://localhost:3000/api/solicitacoes'),
        fetch('http://localhost:3000/api/vendedores'),
        fetch('http://localhost:3000/api/clientes')
      ]);

      if (!solicitacoesResponse.ok) {
        throw new Error(`HTTP error! status: ${solicitacoesResponse.status} for solicitacoes`);
      }
      if (!vendedoresResponse.ok) {
        throw new Error(`HTTP error! status: ${vendedoresResponse.status} for vendedores`);
      }
      if (!clientesResponse.ok) {
        throw new Error(`HTTP error! status: ${clientesResponse.status} for clientes`);
      }

      const solicitacoesData: Solicitacao[] = await solicitacoesResponse.json();
      const vendedoresData: Vendedor[] = await vendedoresResponse.json();
      const clientesData: Cliente[] = await clientesResponse.json();

      setSolicitacoes(solicitacoesData);
      setVendedores(vendedoresData);
      setClientes(clientesData);
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao carregar dados: ${message}`);
      console.error("Erro ao carregar dados:", e);
    } finally {
      setLoading(false);
    }
  };

  const salvarSolicitacao = async (solicitacao: Solicitacao) => {
    setError(null);
    setSuccess(null); // Reset success message
    try {
      let response;
      if (solicitacao.id) {
        // Update existing solicitacao
        response = await fetch(`http://localhost:3000/api/solicitacoes/${solicitacao.id}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(solicitacao),
        });
      } else {
        // Create new solicitacao
        response = await fetch('http://localhost:3000/api/solicitacoes', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(solicitacao),
        });
      }

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarDados(); // Reload data after save
      setMostrarForm(false);
      setSolicitacaoEditando(null);
      setSuccess(`Solicitação ${solicitacao.id ? 'atualizada' : 'criada'} com sucesso!`); // Set success message
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao salvar solicitação: ${message}`);
      console.error("Erro ao salvar solicitação:", e);
    }
  };

  const deletarSolicitacao = async (id: number) => {
    if (!window.confirm('Confirmar exclusão?')) {
      return;
    }
    setError(null);
    setSuccess(null); // Reset success message
    try {
      const response = await fetch(`http://localhost:3000/api/solicitacoes/${id}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarDados(); // Reload data after delete
      setSuccess("Solicitação excluída com sucesso!"); // Set success message
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao deletar solicitação: ${message}`);
      console.error("Erro ao deletar solicitação:", e);
    }
  };

  if (loading) {
    return <div className="text-center p-6">Carregando solicitações...</div>;
  }

  // Error display from the initial load should still show.
  // The Alerta component will handle subsequent errors from save/delete.

  return (
    <div className="page-container p-6 bg-white shadow-md rounded-lg">
      
      {/* Display Alerta for success and error messages */}
      {success && <Alerta message={success} onClose={() => setSuccess(null)} />}
      {error && <Alerta message={error} onClose={() => setError(null)} />}

      <div className="page-header flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-800">Gerenciar Solicitações</h1>
        <button 
          onClick={() => { setSolicitacaoEditando(null); setMostrarForm(true); }}
          className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition-colors"
        >
          + Nova Solicitação
        </button>
      </div>

      <Modal isOpen={mostrarForm} onClose={() => { setMostrarForm(false); setSolicitacaoEditando(null); }}>
        <SolicitacaoForm
          solicitacao={solicitacaoEditando}
          vendedores={vendedores}
          clientes={clientes}
          onSave={salvarSolicitacao}
          onCancel={() => { setMostrarForm(false); setSolicitacaoEditando(null); }}
        />
      </Modal>

      <div className="table-container overflow-x-auto">
        <table className="min-w-full bg-white border border-gray-200">
          <thead>
            <tr className="bg-gray-100 border-b">
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Número</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Vendedor</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Cliente</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Data</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Situação</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Ações</th>
            </tr>
          </thead>
          <tbody>
            {solicitacoes.map(solicitacao => (
              <tr key={solicitacao.id} className="border-b hover:bg-gray-50">
                <td className="py-3 px-4 text-sm text-gray-700">{solicitacao.numero}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{vendedores.find(v => v.id === solicitacao.vendedor_id)?.nome || 'N/A'}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{clientes.find(c => c.id === solicitacao.cliente_id)?.nome || 'N/A'}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{new Date(solicitacao.data_solicitacao).toLocaleDateString()}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{solicitacao.situacao}</td>
                <td className="py-3 px-4 text-sm">
                  <button 
                    onClick={() => { setSolicitacaoEditando(solicitacao); setMostrarForm(true); }}
                    className="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-3 rounded-md mr-2 transition-colors"
                  >
                    Editar
                  </button>
                  <button 
                    onClick={() => deletarSolicitacao(solicitacao.id!)}
                    className="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-3 rounded-md transition-colors"
                  >
                    Excluir
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

const SolicitacaoForm: React.FC<{
  solicitacao: Solicitacao | null;
  vendedores: Vendedor[];
  clientes: Cliente[];
  onSave: (solicitacao: Solicitacao) => void;
  onCancel: () => void;
}> = ({ solicitacao, vendedores, clientes, onSave, onCancel }) => {
  const [formData, setFormData] = useState<Solicitacao>(
    solicitacao || {
      numero: '',
      vendedor_id: 0,
      cliente_id: 0,
      data_solicitacao: new Date().toISOString().split('T')[0],
      situacao: 'Pendente',
    }
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <div className="max-w-4xl w-full bg-white shadow-2xl rounded-2xl p-10">
        <h2 className="text-4xl font-bold text-gray-800 text-center mb-4">
            {solicitacao ? 'Editar' : 'Nova'} Solicitação
        </h2>
        <p className="text-center text-gray-600 mb-8 text-lg">
            Preencha os dados para {solicitacao ? 'atualizar a' : 'criar uma nova'} solicitação.
        </p>

      <form onSubmit={handleSubmit} className="space-y-8">
        <div>
            <label className="block text-xl font-semibold text-gray-700 mb-2">
                1. Informações da Solicitação
            </label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <input
                    type="text"
                    placeholder="Número da Solicitação"
                    value={formData.numero}
                    onChange={e => setFormData({ ...formData, numero: e.target.value })}
                    required
                    className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                <input
                    type="date"
                    value={formData.data_solicitacao}
                    onChange={e => setFormData({ ...formData, data_solicitacao: e.target.value })}
                    required
                    className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
            </div>
        </div>

        <div>
            <label className="block text-xl font-semibold text-gray-700 mb-2">
                2. Cliente e Vendedor
            </label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <select
                    id="vendedor_id"
                    value={formData.vendedor_id}
                    onChange={e => setFormData({ ...formData, vendedor_id: parseInt(e.target.value) })}
                    required
                    className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                    <option value="">Selecione um Vendedor</option>
                    {vendedores.map(vendedor => (
                        <option key={vendedor.id} value={vendedor.id}>
                        {vendedor.nome}
                        </option>
                    ))}
                </select>
                <select
                    id="cliente_id"
                    value={formData.cliente_id}
                    onChange={e => setFormData({ ...formData, cliente_id: parseInt(e.target.value) })}
                    required
                    className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                    <option value="">Selecione um Cliente</option>
                    {clientes.map(cliente => (
                        <option key={cliente.id} value={cliente.id}>
                        {cliente.nome}
                        </option>
                    ))}
                </select>
            </div>
        </div>

        <div>
            <label htmlFor="situacao" className="block text-xl font-semibold text-gray-700 mb-2">
                3. Situação
            </label>
            <input
                type="text"
                id="situacao"
                placeholder="Situação"
                value={formData.situacao || ''}
                onChange={e => setFormData({ ...formData, situacao: e.target.value })}
                className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
        </div>

        <div className="form-actions flex justify-center gap-6 pt-4">
            <button
                type="button"
                onClick={onCancel}
                className="w-1/3 bg-gray-500 hover:bg-gray-600 text-white font-bold text-xl py-4 px-8 rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300"
            >
                Cancelar
            </button>
            <button
                type="submit"
                className="w-1/3 bg-green-600 hover:bg-green-700 text-white font-bold text-xl py-4 px-8 rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300"
            >
                Salvar
            </button>
        </div>
      </form>
    </div>
  );
};

export default Solicitacoes;
