// src/pages/Usuarios.tsx
import React, { useState, useEffect } from 'react';
import Modal from '../components/Modal';

interface Usuario {
  id?: number; // ID is optional for new entries
  nome: string;
  senha_hash: string; // Stored as hash in DB, but for simplicity in form, we'll treat it as a string input
  ativo?: boolean;
  data_criacao?: string; // TIMESTAMP type
}

import React, { useState, useEffect } from 'react';
import Modal from '../components/Modal';
import Alerta from '../components/Alerta'; // Import Alerta

interface Usuario {
  id?: number; // ID is optional for new entries
  nome: string;
  senha_hash: string; // Stored as hash in DB, but for simplicity in form, we'll treat it as a string input
  ativo?: boolean;
  data_criacao?: string; // TIMESTAMP type
}

const Usuarios: React.FC = () => {
  const [usuarios, setUsuarios] = useState<Usuario[]>([]);
  const [mostrarForm, setMostrarForm] = useState(false);
  const [usuarioEditando, setUsuarioEditando] = useState<Usuario | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null); // Add success state

  useEffect(() => {
    carregarUsuarios();
  }, []);

  const carregarUsuarios = async () => {
    setLoading(true);
    setError(null);
    // Do not reset success here so message can persist after reload
    try {
      const response = await fetch('http://localhost:3000/api/usuarios');
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data: Usuario[] = await response.json();
      setUsuarios(data);
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao carregar usuários: ${message}`);
      console.error("Erro ao carregar usuários:", e);
    } finally {
      setLoading(false);
    }
  };

  const salvarUsuario = async (usuario: Usuario) => {
    setError(null);
    setSuccess(null); // Reset success message
    try {
      let response;
      if (usuario.id) {
        // Update existing usuario
        response = await fetch(`http://localhost:3000/api/usuarios/${usuario.id}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(usuario),
        });
      } else {
        // Create new usuario
        response = await fetch('http://localhost:3000/api/usuarios', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(usuario),
        });
      }

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarUsuarios(); // Reload usuarios after save
      setMostrarForm(false);
      setUsuarioEditando(null);
      setSuccess(`Usuário ${usuario.id ? 'atualizado' : 'criado'} com sucesso!`); // Set success message
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao salvar usuário: ${message}`);
      console.error("Erro ao salvar usuário:", e);
    }
  };

  const deletarUsuario = async (id: number) => {
    if (!window.confirm('Confirmar exclusão?')) {
      return;
    }
    setError(null);
    setSuccess(null); // Reset success message
    try {
      const response = await fetch(`http://localhost:3000/api/usuarios/${id}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      await carregarUsuarios(); // Reload usuarios after delete
      setSuccess("Usuário excluído com sucesso!"); // Set success message
    } catch (e: unknown) { // Changed from any to unknown
      let message = "Erro desconhecido";
      if (e instanceof Error) {
        message = e.message;
      }
      setError(`Falha ao deletar usuário: ${message}`);
      console.error("Erro ao deletar usuário:", e);
    }
  };

  if (loading) {
    return <div className="text-center p-6">Carregando usuários...</div>;
  }

  // Error display from the initial load should still show.
  // The Alerta component will handle subsequent errors from save/delete.

  return (
    <div className="page-container p-6 bg-white shadow-md rounded-lg">
      
      {/* Display Alerta for success and error messages */}
      {success && <Alerta message={success} onClose={() => setSuccess(null)} />}
      {error && <Alerta message={error} onClose={() => setError(null)} />}

      <div className="page-header flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-800">Gerenciar Usuários</h1>
        <button 
          onClick={() => { setUsuarioEditando(null); setMostrarForm(true); }}
          className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition-colors"
        >
          + Novo Usuário
        </button>
      </div>

      <Modal isOpen={mostrarForm} onClose={() => { setMostrarForm(false); setUsuarioEditando(null); }}>
        <UsuarioForm
          usuario={usuarioEditando}
          onSave={salvarUsuario}
          onCancel={() => { setMostrarForm(false); setUsuarioEditando(null); }}
        />
      </Modal>

      <div className="table-container overflow-x-auto">
        <table className="min-w-full bg-white border border-gray-200">
          <thead>
            <tr className="bg-gray-100 border-b">
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Nome</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Ativo</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Data Criação</th>
              <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">Ações</th>
            </tr>
          </thead>
          <tbody>
            {usuarios.map(usuario => (
              <tr key={usuario.id} className="border-b hover:bg-gray-50">
                <td className="py-3 px-4 text-sm text-gray-700">{usuario.nome}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{usuario.ativo ? 'Sim' : 'Não'}</td>
                <td className="py-3 px-4 text-sm text-gray-700">{new Date(usuario.data_criacao!).toLocaleDateString()}</td>
                <td className="py-3 px-4 text-sm">
                  <button 
                    onClick={() => { setUsuarioEditando(usuario); setMostrarForm(true); }}
                    className="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-3 rounded-md mr-2 transition-colors"
                  >
                    Editar
                  </button>
                  <button 
                    onClick={() => deletarUsuario(usuario.id!)}
                    className="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-3 rounded-md transition-colors"
                  >
                    Excluir
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

// Componente de formulário reutilizável
const UsuarioForm: React.FC<{ 
  usuario: Usuario | null; 
  onSave: (usuario: Usuario) => void; 
  onCancel: () => void 
}> = ({ usuario, onSave, onCancel }) => {
  const [formData, setFormData] = useState<Usuario>(usuario || {
    nome: '', senha_hash: '', ativo: true
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="form-container bg-white p-8 rounded-lg shadow-xl w-full max-w-md">
      <h2 className="text-2xl font-bold mb-6 text-gray-800">{usuario ? 'Editar' : 'Novo'} Usuário</h2>
      
      <div className="mb-4">
        <label htmlFor="nome" className="block text-gray-700 text-sm font-bold mb-2">Nome:</label>
        <input
          type="text"
          id="nome"
          placeholder="Nome de Usuário"
          value={formData.nome}
          onChange={e => setFormData({...formData, nome: e.target.value})}
          required
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        />
      </div>

      <div className="mb-4">
        <label htmlFor="senha_hash" className="block text-gray-700 text-sm font-bold mb-2">Senha:</label>
        <input
          type="password"
          id="senha_hash"
          placeholder="Senha"
          value={formData.senha_hash}
          onChange={e => setFormData({...formData, senha_hash: e.target.value})}
          required={!usuario} // Password is required for new users
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        />
      </div>

      <div className="mb-6 flex items-center">
        <input
          type="checkbox"
          id="ativo"
          checked={formData.ativo}
          onChange={e => setFormData({...formData, ativo: e.target.checked})}
          className="mr-2 leading-tight"
        />
        <label htmlFor="ativo" className="text-gray-700 text-sm font-bold">Ativo</label>
      </div>
      
      <div className="form-actions flex justify-end gap-4">
        <button 
          type="submit"
          className="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-md transition-colors"
        >
          Salvar
        </button>
        <button 
          type="button" 
          onClick={onCancel}
          className="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-md transition-colors"
        >
          Cancelar
        </button>
      </div>
    </form>
  );
};

export default Usuarios;

// src/routes/usuarios/+page.svelte
<script lang="ts">
    import Users from "@lucide/svelte/icons/users";
    import * as Card from "$lib/components/ui/card/index.js";
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
    import * as Table from "$lib/components/ui/table/index.js";
    import { Button } from "$lib/components/ui/button/index";
    import { Input } from "$lib/components/ui/input/index";
    import { Label } from "@/components/ui/label/index";
    import db, { queryHelper } from "@/db/db.svelte";
    import { Checkbox } from "@/components/ui/checkbox/index";
    import type { Usuario } from "$lib/types";
    import Ellipsis from "@lucide/svelte/icons/ellipsis";
    import PencilLine from "@lucide/svelte/icons/pencil-line";
    import Plus from "@lucide/svelte/icons/plus";
    import Trash2 from "@lucide/svelte/icons/trash-2";
    import Search from "@lucide/svelte/icons/search";
    import { onMount } from "svelte";
    import { toast } from "svelte-sonner";

    let usuarios = $state<Array<Usuario>>([]);
    let dialog = $state<string | null>(null);
    let searchQuery = $state("");

    let filteredUsuarios = $derived(
        searchQuery
            ? usuarios.filter((u) =>
                  u.nome.toLowerCase().includes(searchQuery.toLowerCase()),
              )
            : usuarios,
    );

    let usuarioData = $state<Partial<Usuario>>({
        nome: "",
        senha_hash: "",
        ativo: true,
    });

    async function save() {
        try {
            const dataToSave = { ...usuarioData };
            delete (dataToSave as any).data_criacao;

            let q = queryHelper(dataToSave);
            let query = "";

            if (dataToSave.id) {
                query = `UPDATE usuarios SET ${q.setClauses} WHERE id = ${dataToSave.id}`;
            } else {
                query = `INSERT INTO usuarios (${q.columns}) VALUES (${q.placeholders})`;
            }

            await db.execute(query, q.values);

            await load();
            dialog = null;
            toast.success(
                `Usuário ${dataToSave.id ? "atualizado" : "criado"} com sucesso!`,
            );
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            toast.error(`Falha ao salvar usuário: ${message}`);
            console.error("Erro ao salvar usuário:", e);
        }
    }

    async function delete_(id: number) {
        if (!confirm("Tem certeza que deseja excluir este usuário?")) return;
        try {
            await db.execute("DELETE FROM usuarios WHERE id = $1", [id]);
            await load();
            toast.success("Usuário excluído com sucesso!");
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            toast.error(`Falha ao deletar usuário: ${message}`);
            console.error("Erro ao deletar usuário:", e);
        }
    }

    async function load() {
        try {
            usuarios = (await db.select(
                "SELECT * FROM usuarios",
                [],
            )) as Array<Usuario>;
        } catch (e: unknown) {
            let message = "Erro desconhecido";
            if (e instanceof Error) {
                message = e.message;
            }
            toast.error(`Falha ao carregar usuários: ${message}`);
            console.error("Erro ao carregar usuários:", e);
        }
    }

    onMount(() => load());

    function resetUsuarioData() {
        usuarioData = {
            nome: "",
            senha_hash: "",
            ativo: true,
        };
    }
</script>

<Card.Root class="m-10">
    <Card.Header class="flex flex-row items-center">
        <div>
            <Card.Title class="text-3xl flex items-center gap-2">
                <Users class="h-8 w-8 text-primary" />
                Gerenciamento de Usuários
            </Card.Title>
            <Card.Description
                >Gerencie os usuários do sistema e suas permissões.</Card.Description
            >
        </div>
        <Button
            class="ml-auto cursor-pointer"
            variant="outline"
            size="lg"
            onclick={() => {
                resetUsuarioData();
                dialog = "new";
            }}
        >
            Novo usuário
            <Plus class="ml-2 h-4 w-4" />
        </Button>
    </Card.Header>
    <Card.Content>
        <div class="mb-6 flex items-center gap-4">
            <div class="relative flex-1 max-w-sm">
                <Search
                    class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"
                />
                <Input
                    type="search"
                    placeholder="Pesquisar por nome ou usuário..."
                    class="pl-8"
                    bind:value={searchQuery}
                />
            </div>
        </div>

        <Table.Root>
            <Table.Header>
                <Table.Row>
                    <Table.Head>Nome</Table.Head>
                    <!-- <Table.Head>Usuário</Table.Head> -->
                    <Table.Head>Ativo</Table.Head>
                    <Table.Head>Data Criação</Table.Head>
                    <Table.Head class="w-12.5"></Table.Head>
                </Table.Row>
            </Table.Header>
            <Table.Body>
                {#each filteredUsuarios as usuario (usuario.id)}
                    <Table.Row>
                        <Table.Cell class="font-medium"
                            >{usuario.nome}</Table.Cell
                        >
                        <Table.Cell>
                            <span
                                class={`px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                                    usuario.ativo
                                        ? "bg-green-100 text-green-800"
                                        : "bg-red-100 text-red-800"
                                }`}
                            >
                                {usuario.ativo ? "Ativo" : "Inativo"}
                            </span>
                        </Table.Cell>
                        <Table.Cell
                            >{new Date(usuario.data_criacao).toLocaleDateString(
                                "pt-BR",
                            )}</Table.Cell
                        >
                        <Table.Cell>
                            <Button
                                variant="ghost"
                                size="icon-lg"
                                onclick={() => {
                                    usuarioData = { ...usuario };
                                    dialog = "edit";
                                }}
                            >
                                <PencilLine
                                    class="h-4 w-4 stroke-3 stroke-lime-400"
                                />
                            </Button>
                            <Button
                                variant="ghost"
                                size="icon-lg"
                                class="text-destructive focus:text-destructive"
                                onclick={() => delete_(usuario.id)}
                            >
                                <Trash2
                                    class="h-4 w-4 stroke-3 stroke-red-500"
                                />
                            </Button>
                        </Table.Cell>
                    </Table.Row>
                {:else}
                    <Table.Row>
                        <Table.Cell
                            colspan={4}
                            class="text-center py-10 text-muted-foreground"
                        >
                            Nenhum usuário encontrado.
                        </Table.Cell>
                    </Table.Row>
                {/each}
            </Table.Body>
        </Table.Root>
    </Card.Content>
</Card.Root>

<Dialog.Root
    open={dialog != null}
    onOpenChange={(e) => {
        if (!e) {
            dialog = null;
        }
    }}
>
    <Dialog.Content class="sm:max-w-[425px]">
        <Dialog.Header>
            <Dialog.Title>
                {dialog === "new" ? "Novo Usuário" : "Editar Usuário"}
            </Dialog.Title>
            <Dialog.Description>
                Preencha os dados do usuário abaixo.
            </Dialog.Description>
        </Dialog.Header>

        <div class="grid gap-4 py-4">
            <div class="grid gap-2">
                <Label for="nome">Nome de Usuário</Label>
                <Input
                    id="nome"
                    bind:value={usuarioData.nome}
                    placeholder="Ex: admin"
                />
            </div>
            <div class="grid gap-2">
                <Label for="senha">Senha</Label>
                <Input
                    id="senha"
                    type="password"
                    bind:value={usuarioData.senha_hash}
                    placeholder={dialog === "edit"
                        ? "Deixe em branco para não alterar"
                        : "Senha do usuário"}
                />
            </div>
            <div class="flex items-center space-x-2">
                <Checkbox id="ativo" bind:checked={usuarioData.ativo} />
                <Label
                    for="ativo"
                    class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                >
                    Usuário Ativo
                </Label>
            </div>
        </div>

        <Dialog.Footer>
            <Button variant="outline" onclick={() => (dialog = null)}
                >Cancelar</Button
            >
            <Button onclick={save}>Salvar</Button>
        </Dialog.Footer>
    </Dialog.Content>
</Dialog.Root>
