// src/routes/compras/+page.svelte
<script lang="ts">
    import { Button } from "$lib/components/ui/button/index";
    import * as Card from "$lib/components/ui/card/index.js";
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import { Input } from "$lib/components/ui/input/index";
    import { Label } from "$lib/components/ui/label/index";
    import * as Table from "$lib/components/ui/table/index.js";
    import type { CompraItem, Fornecedor, Produto } from "$lib/types";
    import Plus from "@lucide/svelte/icons/plus";
    import Search from "@lucide/svelte/icons/search";
    import ShoppingBag from "@lucide/svelte/icons/shopping-bag";
    import Trash2 from "@lucide/svelte/icons/trash-2";
    import db, { queryHelper } from "@/db/db.svelte";
    import { onMount } from "svelte";
    import { toast } from "svelte-sonner";

    let compras = $state<Array<any>>([]);
    let fornecedores = $state<Array<Fornecedor>>([]);
    let produtos = $state<Array<Produto>>([]);
    let dialog = $state<string | null>(null);
    let searchQuery = $state("");

    let filteredCompras = $derived(
        compras.filter(
            (c) =>
                c.numero_pedido
                    .toLowerCase()
                    .includes(searchQuery.toLowerCase()) ||
                c.fornecedor_razao_social
                    ?.toLowerCase()
                    .includes(searchQuery.toLowerCase()),
        ),
    );

    // Form state for a new Compra
    let compraData = $state({
        numero_pedido: "",
        fornecedor_id: 0,
        data_pedido: new Date().toISOString().split("T")[0],
        situacao: "Pendente",
        observacoes: "",
    });

    // Form state for items within a Compra
    let items = $state<
        Array<Partial<CompraItem> & { descricao?: string; codigo?: string }>
    >([]);
    let currentItem = $state({
        produto_id: 0,
        quantidade: 1,
        preco_compra: 0,
        desconto: 0,
    });

    let totalPrice = $derived(
        items.reduce((acc, item) => acc + (item.valor_total || 0), 0),
    );

    async function addItem() {
        if (!currentItem.produto_id || currentItem.quantidade <= 0) {
            toast.error("Selecione um produto e quantidade válidos.");
            return;
        }

        const produto = produtos.find((p) => p.id === currentItem.produto_id);
        if (!produto) return;

        const valor_total =
            currentItem.quantidade *
            currentItem.preco_compra *
            (1 - currentItem.desconto / 100);

        items.push({
            ...currentItem,
            valor_total,
            descricao: produto.descricao,
            codigo: produto.codigo,
        });

        // Reset current item form
        currentItem = {
            produto_id: 0,
            quantidade: 1,
            preco_compra: 0,
            desconto: 0,
        };
    }

    function removeItem(index: number) {
        items.splice(index, 1);
    }

    async function save() {
        if (!compraData.fornecedor_id || items.length === 0) {
            toast.error("Preencha o fornecedor e adicione pelo menos um item.");
            return;
        }

        try {
            // First, insert the compra
            const compraToInsert = {
                ...compraData,
                valor_total_pedido: totalPrice,
                valor_total_nota: totalPrice,
            };

            let q = queryHelper(compraToInsert);
            const res = (await db.execute(
                `INSERT INTO compras (${q.columns}) VALUES (${q.placeholders})`,
                q.values,
            )) as any;
            const compraId = res.lastInsertId;

            // Then, insert the items
            for (const item of items) {
                const itemToInsert = {
                    compra_id: compraId,
                    produto_id: item.produto_id,
                    variacao_id: item.variacao_id || null,
                    quantidade: item.quantidade,
                    preco_compra: item.preco_compra,
                    desconto: item.desconto || 0,
                    valor_total: item.valor_total,
                };
                let qi = queryHelper(itemToInsert);
                await db.execute(
                    `INSERT INTO compra_itens (${qi.columns}) VALUES (${qi.placeholders})`,
                    qi.values,
                );
            }

            toast.success("Compra realizada com sucesso!");
            dialog = null;
            await load();
        } catch (e: any) {
            toast.error(e.message || "Erro ao salvar compra");
            console.error(e);
        }
    }

    async function load() {
        try {
            compras = (await db.select(
                `
                SELECT c.*, f.razao_social as fornecedor_razao_social 
                FROM compras c
                JOIN fornecedores f ON c.fornecedor_id = f.id
            `,
                [],
            )) as Array<any>;

            fornecedores = (await db.select(
                "SELECT * FROM fornecedores",
                [],
            )) as Array<Fornecedor>;
            produtos = (await db.select(
                "SELECT * FROM produtos",
                [],
            )) as Array<Produto>;
        } catch (e: any) {
            console.error(e);
            toast.error("Erro ao carregar dados do banco de dados.");
        }
    }

    onMount(() => load());

    function formatCurrency(value: number) {
        return value.toLocaleString("pt-BR", {
            style: "currency",
            currency: "BRL",
        });
    }

    function resetForm() {
        compraData = {
            numero_pedido: "",
            fornecedor_id: 0,
            data_pedido: new Date().toISOString().split("T")[0],
            situacao: "Pendente",
            observacoes: "",
        };
        items = [];
    }
</script>

<Card.Root class="m-10">
    <Card.Header class="flex flex-row items-center">
        <div>
            <Card.Title class="text-3xl">Compras & Pedidos</Card.Title>
            <Card.Description>
                Gerencie as entradas de estoque e pedidos aos fornecedores.
            </Card.Description>
        </div>
        <Button
            class="ml-auto cursor-pointer"
            variant="outline"
            size="lg"
            onclick={() => {
                resetForm();
                dialog = "new";
            }}
        >
            Nova compra
            <Plus class="ml-2 h-4 w-4" />
        </Button>
    </Card.Header>
    <Card.Content>
        <div class="mb-6 flex items-center gap-4">
            <div class="relative flex-1 max-w-sm">
                <Search
                    class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"
                />
                <Input
                    type="search"
                    placeholder="Pesquisar por pedido ou fornecedor..."
                    class="pl-8"
                    bind:value={searchQuery}
                />
            </div>
        </div>

        <Table.Root>
            <Table.Header>
                <Table.Row>
                    <Table.Head>Nº Pedido</Table.Head>
                    <Table.Head>Fornecedor</Table.Head>
                    <Table.Head>Data</Table.Head>
                    <Table.Head class="text-right">Valor Total</Table.Head>
                    <Table.Head>Situação</Table.Head>
                </Table.Row>
            </Table.Header>
            <Table.Body>
                {#each filteredCompras as compra (compra.id)}
                    <Table.Row>
                        <Table.Cell class="font-bold">
                            {compra.numero_pedido}
                        </Table.Cell>
                        <Table.Cell>{compra.fornecedor_razao_social}</Table.Cell
                        >
                        <Table.Cell>
                            {new Date(compra.data_pedido).toLocaleDateString(
                                "pt-BR",
                            )}
                        </Table.Cell>
                        <Table.Cell class="text-right font-medium">
                            {formatCurrency(compra.valor_total_pedido || 0)}
                        </Table.Cell>
                        <Table.Cell>
                            <span
                                class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-muted"
                            >
                                {compra.situacao}
                            </span>
                        </Table.Cell>
                    </Table.Row>
                {:else}
                    <Table.Row>
                        <Table.Cell
                            colspan={5}
                            class="text-center py-10 text-muted-foreground"
                        >
                            Nenhuma compra encontrada.
                        </Table.Cell>
                    </Table.Row>
                {/each}
            </Table.Body>
        </Table.Root>
    </Card.Content>
</Card.Root>

<Dialog.Root
    open={dialog != null}
    onOpenChange={(e) => {
        if (!e) {
            dialog = null;
        }
    }}
>
    <Dialog.Content class="sm:max-w-200 max-h-[90vh] flex flex-col">
        <Dialog.Header>
            <Dialog.Title>Nova Compra</Dialog.Title>
            <Dialog.Description
                >Preencha os dados do pedido e adicione os itens abaixo.</Dialog.Description
            >
        </Dialog.Header>

        <div class="flex-1 overflow-y-auto pr-2 space-y-6 py-4">
            <div class="grid grid-cols-3 gap-4">
                <div class="grid gap-2">
                    <Label for="num">Nº Pedido</Label>
                    <Input id="num" bind:value={compraData.numero_pedido} />
                </div>
                <div class="grid gap-2">
                    <Label for="forn">Fornecedor</Label>
                    <select
                        id="forn"
                        bind:value={compraData.fornecedor_id}
                        class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                    >
                        <option value={0}>Selecione...</option>
                        {#each fornecedores as f}
                            <option value={f.id}>{f.razao_social}</option>
                        {/each}
                    </select>
                </div>
                <div class="grid gap-2">
                    <Label for="date">Data</Label>
                    <Input
                        id="date"
                        type="date"
                        bind:value={compraData.data_pedido}
                    />
                </div>
            </div>

            <div class="rounded-lg border bg-muted/40 p-4 space-y-4">
                <header class="flex items-center gap-2 font-semibold">
                    <ShoppingBag class="h-4 w-4" />
                    Adicionar Item
                </header>
                <div class="grid grid-cols-4 gap-4">
                    <div class="grid gap-2 col-span-2">
                        <Label>Produto</Label>
                        <select
                            bind:value={currentItem.produto_id}
                            onchange={() => {
                                const p = produtos.find(
                                    (p) => p.id === currentItem.produto_id,
                                );
                                if (p)
                                    currentItem.preco_compra =
                                        p.preco_compra || 0;
                            }}
                            class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                        >
                            <option value={0}>Selecione um produto...</option>
                            {#each produtos as p}
                                <option value={p.id}>
                                    {p.codigo} - {p.descricao}
                                </option>
                            {/each}
                        </select>
                    </div>
                    <div class="grid gap-2">
                        <Label>Qtd</Label>
                        <Input
                            type="number"
                            bind:value={currentItem.quantidade}
                            min="1"
                        />
                    </div>
                    <div class="grid gap-2">
                        <Label>Preço Unit.</Label>
                        <Input
                            type="number"
                            bind:value={currentItem.preco_compra}
                            step="0.01"
                        />
                    </div>
                </div>
                <Button variant="secondary" class="w-full" onclick={addItem}>
                    Adicionar Item à Lista
                </Button>
            </div>

            {#if items.length > 0}
                <div class="rounded-lg border">
                    <Table.Root>
                        <Table.Header>
                            <Table.Row>
                                <Table.Head>Produto</Table.Head>
                                <Table.Head class="text-right">Qtd</Table.Head>
                                <Table.Head class="text-right">
                                    Unitário
                                </Table.Head>
                                <Table.Head class="text-right">
                                    Subtotal
                                </Table.Head>
                                <Table.Head></Table.Head>
                            </Table.Row>
                        </Table.Header>
                        <Table.Body>
                            {#each items as item, i}
                                <Table.Row>
                                    <Table.Cell>
                                        <span class="font-medium">
                                            {item.codigo}
                                        </span>
                                        <span
                                            class="block text-xs text-muted-foreground"
                                        >
                                            {item.descricao}
                                        </span>
                                    </Table.Cell>
                                    <Table.Cell class="text-right">
                                        {item.quantidade}
                                    </Table.Cell>
                                    <Table.Cell class="text-right">
                                        {formatCurrency(item.preco_compra || 0)}
                                    </Table.Cell>
                                    <Table.Cell class="text-right font-bold">
                                        {formatCurrency(item.valor_total || 0)}
                                    </Table.Cell>
                                    <Table.Cell>
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            onclick={() => removeItem(i)}
                                        >
                                            <Trash2
                                                class="h-4 w-4 text-destructive"
                                            />
                                        </Button>
                                    </Table.Cell>
                                </Table.Row>
                            {/each}
                        </Table.Body>
                    </Table.Root>
                </div>
                <div class="flex justify-end text-xl font-bold p-2">
                    Total: {formatCurrency(totalPrice || 0)}
                </div>
            {/if}
        </div>

        <Dialog.Footer class="border-t pt-4">
            <Button variant="outline" onclick={() => (dialog = null)}>
                Cancelar
            </Button>
            <Button onclick={save} disabled={items.length === 0}>
                Finalizar Pedido
            </Button>
        </Dialog.Footer>
    </Dialog.Content>
</Dialog.Root>

// old/src/pages/Compras.tsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Alerta from "../components/Alerta";
import Modal from "../components/Modal";
import BuscadorProdutos from "../components/BuscadorProdutos";

// Interfaces based on backend service expectations
interface CompraData {
    numero_pedido: string;
    tipo_pedido?: string;
    fornecedor_id: number;
    data_pedido: string;
    data_entrega?: string;
    data_nota?: string;
    tipo_nota?: string;
    numero_nota?: string;
    valor_total_pedido?: number;
    valor_total_nota?: number;
    desconto?: number;
    frete?: number;
    situacao?: string;
    parcelas?: string;
    observacoes?: string;
}

interface CompraItemData {
    produto_id: number;
    quantidade: number;
    preco_compra: number;
    desconto?: number;
    valor_total: number;
    tamanho?: string;
    cor?: string;
    // Additional frontend-only fields for display
    produto_descricao: string;
    produto_codigo: string;
}

interface Fornecedor {
    id: number;
    razao_social: string;
}

interface Produto {
    id: number;
    descricao: string;
    codigo: string;
    preco_venda: number; // Assuming preco_venda can be used as base for preco_compra
}

interface Compra {
    id: number;
    numero_pedido: string;
    fornecedor_razao_social: string; // Assuming the API returns the supplier's name
    data_pedido: string;
    valor_total_pedido: number;
    situacao: string;
}

const CompraForm: React.FC<{
    onSave: () => void;
    onCancel: () => void;
}> = ({ onSave, onCancel }) => {
    const [fornecedores, setFornecedores] = useState<Fornecedor[]>([]);
    const [compraData, setCompraData] = useState<CompraData>({
        numero_pedido: "",
        fornecedor_id: 0,
        data_pedido: new Date().toISOString().split("T")[0],
        situacao: "Pendente",
    });
    const [itensCompra, setItensCompra] = useState<CompraItemData[]>([]);
    const [produtoSelecionado, setProdutoSelecionado] =
        useState<Produto | null>(null);
    const [quantidadeItem, setQuantidadeItem] = useState(1);
    const [precoCompraItem, setPrecoCompraItem] = useState(0);
    const [descontoItem, setDescontoItem] = useState(0);

    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState<string | null>(null);

    useEffect(() => {
        const fetchFornecedores = async () => {
            setLoading(true);
            try {
                const response = await fetch(
                    "http://localhost:3000/api/fornecedores",
                );
                if (!response.ok) {
                    throw new Error(`HTTP error! status: ${response.status}`);
                }
                const data: Fornecedor[] = await response.json();
                setFornecedores(data);
            } catch (e: unknown) {
                const message =
                    e instanceof Error
                        ? e.message
                        : "Ocorreu um erro desconhecido.";
                setError(`Falha ao carregar fornecedores: ${message}`);
                console.error("Erro ao carregar fornecedores:", e);
            } finally {
                setLoading(false);
            }
        };
        fetchFornecedores();
    }, []);

    useEffect(() => {
        if (produtoSelecionado) {
            setPrecoCompraItem(produtoSelecionado.preco_venda); // Use venda price as default buy price
        }
    }, [produtoSelecionado]);

    const handleAddProdutoToItens = () => {
        if (
            !produtoSelecionado ||
            quantidadeItem <= 0 ||
            precoCompraItem <= 0
        ) {
            setError(
                "Selecione um produto, quantidade e preço de compra válidos.",
            );
            return;
        }

        const valorTotalItem =
            quantidadeItem * precoCompraItem * (1 - descontoItem / 100);

        setItensCompra((prevItens) => [
            ...prevItens,
            {
                produto_id: produtoSelecionado.id,
                quantidade: quantidadeItem,
                preco_compra: precoCompraItem,
                desconto: descontoItem,
                valor_total: valorTotalItem,
                produto_descricao: produtoSelecionado.descricao,
                produto_codigo: produtoSelecionado.codigo,
            },
        ]);

        // Reset item fields
        setProdutoSelecionado(null);
        setQuantidadeItem(1);
        setPrecoCompraItem(0);
        setDescontoItem(0);
        setError(null);
    };

    const handleRemoveItem = (index: number) => {
        setItensCompra((prevItens) => prevItens.filter((_, i) => i !== index));
    };

    const calculateTotalCompra = React.useCallback(() => {
        const total = itensCompra.reduce(
            (sum, item) => sum + item.valor_total,
            0,
        );
        setCompraData((prevData) => ({
            ...prevData,
            valor_total_pedido: total,
            valor_total_nota: total,
        }));
        return total;
    }, [itensCompra]);

    useEffect(() => {
        calculateTotalCompra();
    }, [itensCompra]);

    const handleSubmitCompra = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);
        setSuccess(null);
        setLoading(true);

        if (!compraData.fornecedor_id) {
            setError("Por favor, selecione um fornecedor.");
            setLoading(false);
            return;
        }
        if (itensCompra.length === 0) {
            setError("Adicione pelo menos um item à compra.");
            setLoading(false);
            return;
        }

        try {
            const response = await fetch("http://localhost:3000/api/compras", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ compraData, itensData: itensCompra }),
            });

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(
                    errorData.message || "Falha ao criar a nova compra.",
                );
            }

            const result = await response.json();
            setSuccess(result.message || "Nova compra criada com sucesso!");

            onSave();
        } catch (e: unknown) {
            const message =
                e instanceof Error
                    ? e.message
                    : "Ocorreu um erro desconhecido.";
            setError(`Falha ao registrar compra: ${message}`);
            console.error("Erro ao registrar compra:", e);
        } finally {
            setLoading(false);
        }
    };

    if (loading && fornecedores.length === 0) {
        return <div className="text-center p-6">Carregando dados...</div>;
    }

    return (
        <div className="max-w-4xl w-full bg-white shadow-2xl rounded-2xl p-10">
            <h1 className="text-4xl font-bold text-gray-800 text-center mb-4">
                Nova Compra
            </h1>
            <p className="text-center text-gray-600 mb-8 text-lg">
                Gerencie suas compras de forma simples e eficiente.
            </p>

            {success && (
                <Alerta message={success} onClose={() => setSuccess(null)} />
            )}
            {error && <Alerta message={error} onClose={() => setError(null)} />}

            <form onSubmit={handleSubmitCompra} className="space-y-8">
                {/* Detalhes da Compra */}
                <div>
                    <label className="block text-xl font-semibold text-gray-700 mb-2">
                        1. Detalhes da Compra
                    </label>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <input
                            type="text"
                            id="numero_pedido"
                            placeholder="Número do Pedido"
                            value={compraData.numero_pedido}
                            onChange={(e) =>
                                setCompraData({
                                    ...compraData,
                                    numero_pedido: e.target.value,
                                })
                            }
                            required
                            className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        />
                        <select
                            id="fornecedor_id"
                            value={compraData.fornecedor_id}
                            onChange={(e) =>
                                setCompraData({
                                    ...compraData,
                                    fornecedor_id: parseInt(e.target.value),
                                })
                            }
                            required
                            className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        >
                            <option value="0">Selecione um Fornecedor</option>
                            {fornecedores.map((fornecedor) => (
                                <option
                                    key={fornecedor.id}
                                    value={fornecedor.id}
                                >
                                    {fornecedor.razao_social}
                                </option>
                            ))}
                        </select>
                        <input
                            type="date"
                            id="data_pedido"
                            value={compraData.data_pedido}
                            onChange={(e) =>
                                setCompraData({
                                    ...compraData,
                                    data_pedido: e.target.value,
                                })
                            }
                            required
                            className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        />
                    </div>
                </div>

                {/* Adicionar Itens à Compra */}
                <div>
                    <label className="block text-xl font-semibold text-gray-700 mb-2">
                        2. Adicionar Itens
                    </label>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
                        <div className="lg:col-span-2">
                            <BuscadorProdutos
                                onProdutoSelecionado={setProdutoSelecionado}
                                produtoInicial={produtoSelecionado}
                            />
                        </div>
                        <input
                            type="number"
                            id="quantidadeItem"
                            placeholder="Quantidade"
                            value={quantidadeItem}
                            onChange={(e) =>
                                setQuantidadeItem(parseInt(e.target.value))
                            }
                            min="1"
                            className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        />
                        <input
                            type="number"
                            id="precoCompraItem"
                            placeholder="Preço de Compra"
                            value={precoCompraItem}
                            onChange={(e) =>
                                setPrecoCompraItem(parseFloat(e.target.value))
                            }
                            step="0.01"
                            className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        />
                        <input
                            type="number"
                            id="descontoItem"
                            placeholder="Desconto (%)"
                            value={descontoItem}
                            onChange={(e) =>
                                setDescontoItem(parseFloat(e.target.value))
                            }
                            min="0"
                            max="100"
                            className="shadow-lg appearance-none border-2 border-gray-200 rounded-lg w-full py-3 px-4 text-gray-700 text-lg leading-tight focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        />
                        <div className="lg:col-span-4 flex justify-end">
                            <button
                                type="button"
                                onClick={handleAddProdutoToItens}
                                className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md"
                            >
                                Adicionar Item
                            </button>
                        </div>
                    </div>

                    {/* Lista de Itens Adicionados */}
                    {itensCompra.length > 0 && (
                        <div className="mt-6">
                            <h3 className="text-lg font-bold mb-2">
                                Itens da Compra:
                            </h3>
                            <div className="overflow-x-auto">
                                <table className="min-w-full bg-white border border-gray-200">
                                    <thead>
                                        <tr className="bg-gray-100">
                                            <th className="py-2 px-3 text-left text-sm font-semibold text-gray-600">
                                                Produto
                                            </th>
                                            <th className="py-2 px-3 text-left text-sm font-semibold text-gray-600">
                                                Qtd
                                            </th>
                                            <th className="py-2 px-3 text-left text-sm font-semibold text-gray-600">
                                                Preço Compra
                                            </th>
                                            <th className="py-2 px-3 text-left text-sm font-semibold text-gray-600">
                                                Desconto
                                            </th>
                                            <th className="py-2 px-3 text-left text-sm font-semibold text-gray-600">
                                                Total
                                            </th>
                                            <th className="py-2 px-3 text-left text-sm font-semibold text-gray-600">
                                                Ações
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {itensCompra.map((item, index) => (
                                            <tr
                                                key={index}
                                                className="border-b"
                                            >
                                                <td className="py-2 px-3 text-sm text-gray-700">
                                                    {item.produto_descricao}
                                                </td>
                                                <td className="py-2 px-3 text-sm text-gray-700">
                                                    {item.quantidade}
                                                </td>
                                                <td className="py-2 px-3 text-sm text-gray-700">
                                                    R$ {item.preco_compra}
                                                </td>
                                                <td className="py-2 px-3 text-sm text-gray-700">
                                                    {item.desconto || 0}%
                                                </td>
                                                <td className="py-2 px-3 text-sm text-gray-700">
                                                    R$ {item.valor_total}
                                                </td>
                                                <td className="py-2 px-3 text-sm">
                                                    <button
                                                        type="button"
                                                        onClick={() =>
                                                            handleRemoveItem(
                                                                index,
                                                            )
                                                        }
                                                        className="text-red-600 hover:text-red-800"
                                                    >
                                                        Remover
                                                    </button>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                            <div className="text-right mt-4 text-lg font-bold text-gray-800">
                                Total da Compra: R${" "}
                                {compraData.valor_total_pedido || "0.00"}
                            </div>
                        </div>
                    )}
                </div>

                <div className="form-actions flex justify-center gap-6 pt-4">
                    <button
                        type="button"
                        onClick={onCancel}
                        className="w-1/3 bg-gray-500 hover:bg-gray-600 text-white font-bold text-xl py-4 px-8 rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300"
                    >
                        Cancelar
                    </button>
                    <button
                        type="submit"
                        className="w-1/3 bg-green-600 hover:bg-green-700 text-white font-bold text-xl py-4 px-8 rounded-xl shadow-lg transform hover:scale-105 transition-all duration-300"
                        disabled={loading}
                    >
                        {loading ? "Salvando..." : "Finalizar Compra"}
                    </button>
                </div>
            </form>
        </div>
    );
};

const Compras: React.FC = () => {
    const navigate = useNavigate();
    const [compras, setCompras] = useState<Compra[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState<string | null>(null);
    const [showModal, setShowModal] = useState(false);

    const fetchCompras = async () => {
        setLoading(true);
        try {
            const response = await fetch("http://localhost:3000/api/compras");
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            const data = await response.json();
            setCompras(data);
        } catch (e: unknown) {
            const message =
                e instanceof Error
                    ? e.message
                    : "Ocorreu um erro desconhecido.";
            setError(`Falha ao carregar compras: ${message}`);
            console.error("Erro ao carregar compras:", e);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchCompras();
    }, []);

    const handleSave = () => {
        setShowModal(false);
        fetchCompras();
        setSuccess("Compra salva com sucesso!");
    };

    if (loading) {
        return <div className="text-center p-6">Carregando compras...</div>;
    }

    return (
        <div className="page-container p-6 bg-white shadow-md rounded-lg">
            {success && (
                <Alerta message={success} onClose={() => setSuccess(null)} />
            )}
            {error && <Alerta message={error} onClose={() => setError(null)} />}

            <div className="page-header flex justify-between items-center mb-6">
                <h1 className="text-3xl font-bold text-gray-800">
                    Gerenciar Compras
                </h1>
                <button
                    onClick={() => setShowModal(true)}
                    className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition-colors"
                >
                    + Nova Compra
                </button>
            </div>

            <Modal isOpen={showModal} onClose={() => setShowModal(false)}>
                <CompraForm
                    onSave={handleSave}
                    onCancel={() => setShowModal(false)}
                />
            </Modal>

            <div className="table-container overflow-x-auto">
                <table className="min-w-full bg-white border border-gray-200">
                    <thead>
                        <tr className="bg-gray-100 border-b">
                            <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">
                                Nº Pedido
                            </th>
                            <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">
                                Fornecedor
                            </th>
                            <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">
                                Data
                            </th>
                            <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">
                                Valor Total
                            </th>
                            <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">
                                Situação
                            </th>
                            <th className="py-3 px-4 text-left text-sm font-semibold text-gray-600">
                                Ações
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {compras.map((compra) => (
                            <tr
                                key={compra.id}
                                className="border-b hover:bg-gray-50"
                            >
                                <td className="py-3 px-4 text-sm text-gray-700">
                                    {compra.numero_pedido}
                                </td>
                                <td className="py-3 px-4 text-sm text-gray-700">
                                    {compra.fornecedor_razao_social}
                                </td>
                                <td className="py-3 px-4 text-sm text-gray-700">
                                    {new Date(
                                        compra.data_pedido,
                                    ).toLocaleDateString()}
                                </td>
                                <td className="py-3 px-4 text-sm text-gray-700">
                                    R$ {compra.valor_total_pedido}
                                </td>
                                <td className="py-3 px-4 text-sm text-gray-700">
                                    {compra.situacao}
                                </td>
                                <td className="py-3 px-4 text-sm">
                                    <button
                                        onClick={() =>
                                            navigate(`/compras/${compra.id}`)
                                        }
                                        className="bg-gray-500 hover:bg-gray-600 text-white font-bold py-1 px-3 rounded-md transition-colors"
                                    >
                                        Detalhes
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default Compras;
